### ISSUE TITLE
Can't connect to redis DB

### ISSUE THREAD

**Issue by sbstratos79** [searxng/searxng#1116]
master branch e22dc2ba36bfbd578c8f065975b35e178dce7a13
Installed using official wiki/script

**What happened?**

searXNG can't connect with redis-db

**How To Reproduce**

- Install searXNG
- `./manage redis.build`
- `sudo -H ./manage redis.install`
- `sudo -H ./manage redis.addgrp "${USER}"`
- logout/login
- open sudo ./searx.sh shell
- run `from searx.shared import redisdb` and `redisdb.init()` in python venv
- Get this error:
```
2022-04-18 16:48:29,926 ERROR:searx.shared.redis: can't connet redis DB ...
2022-04-18 16:48:29,927 ERROR:searx.shared.redis:   Error 13 connecting to unix socket: /usr/local/searxng-redis/run/redis.sock. Permission denied.
False
```

**Expected behavior**
Output should be `True`

**Additional context**
I tried `sudo chown searxng-redis:searxng-redis /usr/local/searxng-redis/run/redis.sock` as well. It didn't help.

**Comment by tiekoetter** [comment]
What OS/Distribution are you using?

**Comment by sbstratos79** [comment]
> What OS/Distribution are you using?

Ubuntu 20.04 LTS

**Comment by tiekoetter** [comment]
Is the ``unixsocket`` option enabled in ``/etc/redis/redis.conf``?

**Comment by sbstratos79** [comment]
Yes, I have already enabled it. But wouldn't `searxng-redis` service use the redis.conf located at `/usr/local/searxng-redis/`?

**Comment by tiekoetter** [comment]
You are right. Forget what I just said. That only applies if you install redis via a package manager.

What user did you allow access to redis? You should grant the ``searx`` user access. You can check by running ``groups searx``.

**Comment by sbstratos79** [comment]
I get this output from `groups searx`:
`searx : searx`
I have added my user account to the `searxng-redis` group. Should I add my user account to the searx group as well?

**Comment by tiekoetter** [comment]
Add the searx user to the redis group.

**Comment by sbstratos79** [comment]
Thanks. Adding `searx` to the `redis` and `searx-redix` group did the trick. I think adding it to the `redis` group was unnecessary since it's not using the package manager installed version of redis but I did it anyway just to be on the safe side. I will close the issue now.

**Comment by Twix53791** [comment]
Hello,

I am trying to install a local instance of searxng. I am on arch linux. I followed the step-by-step guide carefully. When I run `python searx/webapp.py` to test it as recommanded, it works, I have got a local instance of searx on my local host, fonctional, but on the terminal I got the following error:

```
(searx-pyenv) [searxng@motherhome searxng-src]$ python searx/webapp.py
2024-03-15 10:53:26,036 ERROR:searx.redisdb: [searxng (968)] can't connect redis DB ...
Traceback (most recent call last):
  File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/redis/connection.py", line 276, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/redis/connection.py", line 277, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/redis/connection.py", line 830, in _connect
    sock.connect(self.path)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/searxng/searxng-src/searx/redisdb.py", line 55, in initialize
    _CLIENT.ping()
  File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/redis/commands/core.py", line 1217, in ping
    return self.execute_command("PING", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/redis/client.py", line 540, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/redis/connection.py", line 1104, in get_connection
    connection.connect()
  File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/redis/connection.py", line 282, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 2 connecting to unix socket: /usr/local/searxng-redis/run/redis.sock. No such file or directory.
2024-03-15 10:53:26,136 ERROR:searx.limiter: The limiter requires Redis, please consult the documentation: https://docs.searxng.org/admin/searx.limiter.html
 * Serving Flask app 'webapp'
 * Debug mode: off
```

I am wondering if it is important to fix it, as searx works nonetheless, and how? Thanx for any clue!

**Comment by return42** [comment]
Did you installed redis?

**Comment by Twix53791** [comment]
Well... no. In fact it was that, redis needed to be installed. Sad than the step by step  guide doesn't explain that. I did'nt want to spend my time to understand how redis works and without removing all the installation steps I have made, I used the installation script and now the problem is resolved.
