### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by x-tk** [searxng/searxng#1171]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
It will not load, so can't use GUI.  In version_frozen.py, I get:
VERSION_STRING = "2022.05.03-31521f3a"
VERSION_TAG = "2022.05.03-31521f3a"
GIT_URL = "https://github.com/searxng/searxng"
GIT_BRANCH = "master"

-->
**How did you install SearXNG?**
unraid docker

**What happened?**
After the latest update, receiving an "Internal Server Error" when loading the page

**How To Reproduce**
Go to the URL.

**Expected behavior**
Page launches as expected

**Screenshots & Logs**
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python3.9/site-packages/flask/app.py", line 1521, in full_dispatch_request
rv = self.preprocess_request()
File "/usr/lib/python3.9/site-packages/flask/app.py", line 1861, in preprocess_request
rv = self.ensure_sync(before_func)()
File "/usr/local/searxng/searx/webapp.py", line 519, in pre_request
preferences = Preferences(themes, list(categories.keys()), engines, plugins) # pylint: disable=redefined-outer-name
File "/usr/local/searxng/searx/preferences.py", line 345, in __init__
'theme': EnumStringSetting(
File "/usr/local/searxng/searx/preferences.py", line 71, in __init__
self._validate_selection(self.value)
File "/usr/local/searxng/searx/preferences.py", line 75, in _validate_selection
raise ValidationException('Invalid value: "{0}"'.format(selection))
searx.preferences.ValidationException: Invalid value: "oscar"
[pid: 192|app: 0|req: 3/4] 172.19.0.## () {36 vars in 581 bytes} [Wed May 4 16:20:10 2022] GET / => generated 265 bytes in 1 msecs (HTTP/1.1 500) 9 headers in 321 bytes (1 switches on core 3)

**Comment by return42** [comment]
You just need to make sure this is set in `settings.yml`:
https://github.com/searxng/searxng/blob/31521f3a465fa2beb7e3fd7ed47621262a28f554/searx/settings.yml#L82

**Comment by ononoki1** [comment]
maybe we should pin this issue. I can foresee that there will be plenty of similar ones
