### ISSUE TITLE
Bug: tineye engine

### ISSUE THREAD

**Issue by matthiasmalta** [searxng/searxng#1449]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.06.14-e67ed894

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 100
  * Parameters: `('422', 'Unprocessable Entity', 'tineye.com')`
  * File name: `searx/search/processors/online.py:96`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
I can reproduce this issue by `!tineye https://docs.searxng.org/_static/searxng-wordmark.svg`

```
ERROR   searx.engines.tineye          : requests exception (search duration : 0.6071255349997955 s, timeout: 9.0 s) : Client error '422 Unprocessable Entity' for url 'https://tineye.com/result_json/?page=1&url=https%3A%2F%2Fdocs.searxng.org%2F_static%2Fsearxng-wordmark.svg'
For more information check: https://httpstatuses.com/422
Traceback (most recent call last):
  File "/share/searxng/searx/search/processors/online.py", line 143, in search
    search_results = self._search_basic(query, params)
  File "/share/searxng/searx/search/processors/online.py", line 127, in _search_basic
    response = self._send_http_request(params)
  File "/share/searxng/searx/search/processors/online.py", line 96, in _send_http_request
    response = req(params['url'], **request_args)
  File "/share/searxng/searx/network/__init__.py", line 111, in get
    return request('get', url, **kwargs)
  File "/share/searxng/searx/network/__init__.py", line 104, in request
    raise_for_httperror(response)
  File "/share/searxng/searx/network/raise_for_httperror.py", line 72, in raise_for_httperror
    resp.raise_for_status()
  File "/share/searxng/local/py3/lib/python3.8/site-packages/httpx/_models.py", line 1508, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '422 Unprocessable Entity' for url 'https://tineye.com/result_json/?page=1&url=https%3A%2F%2Fdocs.searxng.org%2F_static%2Fsearxng-wordmark.svg'
For more information check: https://httpstatuses.com/422

```
