### ISSUE TITLE
Bug: openairepublications engine

### ISSUE THREAD

**Issue by return42** [searxng/searxng#1807]
**Version of SearXNG**

Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.09.24-e36b02350

**How did you install SearXNG?**

    make run

**How To Reproduce**

    !openairepublications 123

**What happened?**

engine openairepublications raise an exception ...

```
Traceback (most recent call last):
  File "SearXNG/searx/search/processors/online.py", line 154, in search
    search_results = self._search_basic(query, params)
  File "SearXNG/searx/search/processors/online.py", line 142, in _search_basic
    return self.engine.response(response)
  File "share/SearXNG/searx/engines/json_engine.py", line 116, in response
    json = loads(resp.text)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 110945 (char 110944)
```

This is because the returned JSON is invalid and can't be parsed by the JSON decoder / see:

  https://api.openaire.eu/search/publications?format=json&page=1&size=10&title=123

The returned JSON contains by example:

    "originalId" : [ { "$" : 0097316595900713 }, 

In JSON a leading zero introduce an octal number (can't contain a 9 or 8), but this number here should be read as a string.

I assume to fix this issue we need to implement our own (dirty) JSONDecoder.

**Technical report**

Error
  * Error: json.decoder.JSONDecodeError
  * Percentage: 40
  * Parameters: `("Expecting ',' delimiter",)`
  * File name: `searx/engines/json_engine.py:111`
  * Function: `response`
  * Code: `json = loads(resp.text)`

**Comment by return42** [comment]
> This is because the returned JSON is invalid and can't be parsed by the JSON decoder / see:
>
>  https://api.openaire.eu/search/publications?format=json&page=1&size=10&title=123
>
> The returned JSON contains by example:
>
>    "originalId" : [ { "$" : 0097316595900713 }, 

Seems [https://api.openaire.eu](https://api.openaire.eu/search/publications?format=json&page=1&size=10&title=123) has fixed the issue / I can't reproduce this issue any longer.
