### ISSUE TITLE
wiby returning parse error in some cases where query inludes the string 'search'

### ISSUE THREAD

**Issue by xpufx** [searxng/searxng#1838]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
docker  2022.10.01-901143f0

**How did you install SearXNG?**
searxng-docker

**What happened?**
Search for 'alsls safdasd search fdlsala' causes a parse error on wiby engine. Change the phrase search to anything else and it doesn't happen. (Though the other search terms also effect the result. It doesn't happen with every combination)

**Screenshots & Logs**
![image](https://user-images.githubusercontent.com/25581961/194044031-92055369-ebef-442d-8d4d-abc2139bda34.png)
![image](https://user-images.githubusercontent.com/25581961/194044134-9fb54400-9a1d-45d3-ab30-35415320f9dd.png)
![image](https://user-images.githubusercontent.com/25581961/194044263-a2095a6c-67cf-4195-85bc-79d72176c5a7.png)
![image](https://user-images.githubusercontent.com/25581961/194044345-4241450a-efd4-484b-9e3c-e92ed41a7cfa.png)

```
2022-10-05 10:53:27,463 WARNING:searx.engines.wiby: ErrorContext('searx/engines/json_engine.py', 111, 'json = loads(resp.text)', 'json.decoder.JSONDecodeError', None, ('Invalid control character at',)) False

2022-10-05 10:53:27,463 ERROR:searx.engines.wiby: exception : Invalid control character at: line 17 column 141 (char 1360)


Traceback (most recent call last):

  File "/usr/local/searxng/searx/search/processors/online.py", line 154, in search

    search_results = self._search_basic(query, params)

  File "/usr/local/searxng/searx/search/processors/online.py", line 142, in _search_basic

    return self.engine.response(response)

  File "/usr/local/searxng/searx/engines/json_engine.py", line 111, in response

    json = loads(resp.text)

  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads

    return _default_decoder.decode(s)

  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode

    obj, end = self.scan_once(s, idx)

json.decoder.JSONDecodeError: Invalid control character at: line 17 column 141 (char 1360)
```

![image](https://user-images.githubusercontent.com/25581961/194044620-782b1acf-95ca-46a3-975f-bd431cb9d3bf.png)

**Comment by allendema** [comment]
This comes from the upstream engine itself.
https://wiby.org/json/?q=alsls+safdasd+search+fdlsala

Copy the result data to a [JSON formatter](https://jsonformatter.curiousconcept.com/) > and there will be an unvalid char.

**Comment by xpufx** [comment]
Ok So it seems like it's about the results returned not the "search" keyword. I will see if they have a place to submit bugs. Thanks.

`    "Snippet": " Best New Search Engine – Virus Prevention – Safe Search Safe l e Best New Search Engine     Attention!   ¡Atención!   Atenç",`

**Comment by wibyweb** [comment]
I applied a fix for this. Should be working now.

**Comment by xpufx** [comment]
Confirmed working. Closing.

**Comment by Robbylikes** [comment]
Wiby is showing a timeout.
