### ISSUE TITLE
searxng rpi container won't start

### ISSUE THREAD

**Issue by N1ghtshad0w** [searxng/searxng#189]
Docker image version
1.0.0-495-30e4a2a2

Platform
RPi3+

Docker run command
`docker run --detach \
           --name searxng \
             --restart unless-stopped \
             -p 8881:8080 \
             -v "${PWD}/searx:/etc/searx" \
             -e "INSTANCE_NAME=searxng" \
             searxng/searxng`

Problem
won't start and keeps looping

![screenshot-2021 07 01-10_43_04](https://user-images.githubusercontent.com/48315620/124095937-6ddc5480-da5a-11eb-925c-811c2cf7f3cb.png)

**Comment by AtomHare** [comment]
I have the same issue on a rpi 4

**Comment by dalf** [comment]
I don't have a ARM hardware, so I can't check locally.

In `${PWD}/searx/uwsgi.ini`, can you:
* remove these lines:
https://github.com/searxng/searxng/blob/7f18cbbee0e0eccc86b78455d4aec38e391318ec/dockerfiles/uwsgi.ini#L26-L33
* add
```
logto = /dev/stdout
```

And start again:
`docker run --detach \ --name searxng \ --restart unless-stopped \ -p 8881:8080 \ -v "${PWD}/searx:/etc/searx" \ -e "INSTANCE_NAME=searxng" \ searxng/searxng`

you should see more details about the error(s).

**Comment by AtomHare** [comment]
Tried that, the container couldn't access `/dev/stdout` (launching with portainer) so I did without, this is the only error i get

```
searx version 1.0.0-552-197fa188,
Use existing /etc/searx/uwsgi.ini,
Use existing /etc/searx/settings.yml,
Listen on 0.0.0.0:8080,
[uWSGI] getting INI configuration from /etc/searx/uwsgi.ini,
[uwsgi-static] added mapping for /static => /usr/local/searx/searx/static,
*** Starting uWSGI 2.0.19.1 (32bit) on [Thu Aug 12 16:02:20 2021] ***,
compiled with version: 10.3.1 20210424 on 05 April 2021 18:18:03,
os: Linux-5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021,
nodename: e59603152fae,
machine: armv7l,
clock source: unix,
pcre jit disabled,
detected number of CPU cores: 4,
current working directory: /usr/local/searx,
detected binary path: /usr/sbin/uwsgi,
chdir() to /usr/local/searx/searx/,
your memory page size is 4096 bytes,
detected max file descriptor number: 1048576,
building mime-types dictionary from file /etc/mime.types...1311 entry found,
lock engine: pthread robust mutexes,
thunder lock: disabled (you can enable it with --thunder-lock),
*** Cache "searxcache" initialized: 11MB (key: 2136 bytes, keys: 4272000 bytes, data: 8192000 bytes, bitmap: 250 bytes) preallocated ***,
uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 4,
Python version: 3.9.5 (default, May 12 2021, 20:44:22)  [GCC 10.3.1 20210424],
Python main interpreter initialized at 0xb68dd8a0,
python threads support enabled,
your server socket listen backlog is limited to 100 connections,
your mercy for graceful operations on workers is 60 seconds,
mapped 327240 bytes (319 KB) for 4 cores,
*** Operational MODE: preforking ***,
added /usr/local/searx/ to pythonpath.,
spawned uWSGI master process (pid: 8),
spawned uWSGI worker 1 (pid: 13, cores: 1),
spawned uWSGI worker 2 (pid: 14, cores: 1),
spawned uWSGI worker 3 (pid: 19, cores: 1),
spawned 4 offload threads for uWSGI worker 1,
spawned 4 offload threads for uWSGI worker 2,
cache sweeper thread enabled,
spawned 4 offload threads for uWSGI worker 4,
spawned uWSGI worker 4 (pid: 23, cores: 1),
spawned 4 offload threads for uWSGI worker 3,
WSGI app 0 (mountpoint='') ready in 7 seconds on interpreter 0xb68dd8a0 pid: 19 (default app),
WSGI app 0 (mountpoint='') ready in 7 seconds on interpreter 0xb68dd8a0 pid: 14 (default app),
WSGI app 0 (mountpoint='') ready in 7 seconds on interpreter 0xb68dd8a0 pid: 23 (default app),
WSGI app 0 (mountpoint='') ready in 7 seconds on interpreter 0xb68dd8a0 pid: 13 (default app),
ERROR:searx.searx.search.processor:yggtorrent engine: Fail to initialize,
Traceback (most recent call last):,
  File "/usr/lib/python3.9/site-packages/httpx/_exceptions.py", line 326, in map_exceptions,
  File "/usr/lib/python3.9/site-packages/httpx/_client.py", line 1492, in _send_single_request,
    (status_code, headers, stream, ext) = await transport.arequest(,
  File "/usr/local/searx/searx/network/client.py", line 136, in arequest,
  File "/usr/local/searx/searx/network/client.py", line 118, in arequest,
    return await super().arequest(method, url, headers, stream, ext),
  File "/usr/lib/python3.9/site-packages/httpx/_transports/default.py", line 169, in arequest,
    return await self._pool.arequest(,
  File "/usr/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 218, in arequest,
    response = await connection.arequest(,
  File "/usr/lib/python3.9/site-packages/httpcore/_async/connection.py", line 93, in arequest,
    self.socket = await self._open_socket(timeout),
  File "/usr/lib/python3.9/site-packages/httpcore/_async/connection.py", line 119, in _open_socket,
    return await self.backend.open_tcp_stream(,
  File "/usr/lib/python3.9/site-packages/httpcore/_backends/asyncio.py", line 270, in open_tcp_stream,
    return SocketStream(,
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__,
    self.gen.throw(type, value, traceback),
  File "/usr/lib/python3.9/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions,
    raise to_exc(exc) from None,
httpcore.ConnectError: Multiple exceptions: [Errno 111] Connection refused, [Errno 99] Address not available,
The above exception was the direct cause of the following exception:,
,
  File "/usr/local/searx/searx/search/processors/abstract.py", line 72, in initialize,
  File "/usr/local/searx/searx/engines/yggtorrent.py", line 42, in init,
    self.engine.init(get_engine_from_settings(self.engine_name)),
    resp = http_get(url, allow_redirects=False),
  File "/usr/local/searx/searx/network/__init__.py", line 136, in get,
    return request('get', url, **kwargs),
  File "/usr/local/searx/searx/network/__init__.py", line 113, in request,
    response = future.result(timeout),
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result,
    return self.__get_result(),
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result,
    raise self._exception,
  File "/usr/local/searx/searx/network/network.py", line 191, in request,
    raise e,
  File "/usr/local/searx/searx/network/network.py", line 186, in request,
    response = await client.request(method, url, **kwargs),
  File "/usr/lib/python3.9/site-packages/httpx/_client.py", line 1361, in request,
    response = await self.send(,
  File "/usr/lib/python3.9/site-packages/httpx/_client.py", line 1396, in send,
    response = await self._send_handling_auth(,
  File "/usr/lib/python3.9/site-packages/httpx/_client.py", line 1434, in _send_handling_auth,
    response = await self._send_handling_redirects(,
  File "/usr/lib/python3.9/site-packages/httpx/_client.py", line 1466, in _send_handling_redirects,
    response = await self._send_single_request(request, timeout),
  File "/usr/lib/python3.9/site-packages/httpx/_exceptions.py", line 343, in map_exceptions,
    raise mapped_exc(message, **kwargs) from exc  # type: ignore,
httpx.ConnectError: Multiple exceptions: [Errno 111] Connection refused, [Errno 99] Address not available

**Comment by dalf** [comment]
> ERROR:searx.searx.search.processor:yggtorrent engine: Fail to initialize,

The logged error comes from the yggtorrent engine.
It should be not stop searxng.

> `httpx.ConnectError: Multiple exceptions: [Errno 111] Connection refused, [Errno 99] Address not available`

It seems searxng tries to connect to an IPv6 and the server doesn't have an IPv6 address.

Can you try to disable the yggtorrent engine ? Comment out or remove these lines:
https://github.com/searxng/searxng/blob/7f18cbbee0e0eccc86b78455d4aec38e391318ec/searx/settings.yml#L1234-L1239

**Comment by AtomHare** [comment]
So I pulled the latest image `searx version 1.0.0-638-7f18cbbe` and it's working like a charm, I should've used the latest release before posting, thank you for your responsiveness dalf !

**Comment by dalf** [comment]
@N1ghtshad0w if the app still doesn't start with the last version, feel free to reopen the issue.
