### ISSUE TITLE
Preferences Crash with "Internal Server Error"

### ISSUE THREAD

**Issue by athlon770** [searxng/searxng#1941]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

2022.11.06-ae54c7d5

**How did you install SearXNG?**

Docker through the Latest Version of UnRaid (Version: 6.11.2) 

**What happened?**

Received two updates at the same time...UnRaid and SearXNG.  Both updates installed clean,  Went to update my SearXNG preferences today and am getting the following...

```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Either the server is overloaded or there is an error in the application.
```

Previous SearXNG Version 2022.10.29-fc9986de running on spare box still works fine.

**How To Reproduce**
I do not have a 3rd UnRaid box to update to see if it breaks. 

**Expected behavior**
Preferences should open and not cause an error

**Screenshots & Logs**

**Additional context**

**Comment by monogoat** [comment]
Also broken on mine, same setup (docker on unraid). Version is reading as 2022.11.06-ae54c7d5. Unraid box is on 6.10.3

**Comment by pacroy9** [comment]
I have the same problem, using Unraid Verion Version: 6.11.1 with searxng - 2022.11.06-ae54c7d5, when accessing the settings, I get the Internal Server Error.

**Comment by dalf** [comment]
What is the result of `docker logs` for the SearXNG container?
It should contain a more detail error.

**Comment by pacroy9** [comment]
> What is the result of `docker logs` for the SearXNG container? It should contain a more detail error.

```
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/searxng/searx/webapp.py", line 1002, in preferences
    checker_results = checker_get_result()
  File "/usr/local/searxng/searx/search/checker/background.py", line 87, in get_result
    serialized_result: Optional[bytes] = client.get(REDIS_RESULT_KEY)
  File "/usr/lib/python3.10/site-packages/redis/commands/core.py", line 1705, in get
    return self.execute_command("GET", name)
  File "/usr/lib/python3.10/site-packages/redis/client.py", line 1235, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 1387, in get_connection
    connection.connect()
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 617, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 2 connecting to unix socket: /usr/local/searxng-redis/run/redis.sock. No such file or directory.
[pid: 20|app: 0|req: 3/7] 192.168.178.3 () {40 vars in 1106 bytes} [Mon Nov  7 20:07:12 2022] GET /preferences => generated 265 bytes in 11 msecs (HTTP/1.1 500) 9 headers in 322 bytes (1 switches on core 0)
2022-11-07 20:13:58,439 ERROR:searx.webapp: Exception on /preferences [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 611, in connect
    sock = self.retry.call_with_retry(
  File "/usr/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 612, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 1129, in _connect
    sock.connect(self.path)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/searxng/searx/webapp.py", line 1002, in preferences
    checker_results = checker_get_result()
  File "/usr/local/searxng/searx/search/checker/background.py", line 87, in get_result
    serialized_result: Optional[bytes] = client.get(REDIS_RESULT_KEY)
  File "/usr/lib/python3.10/site-packages/redis/commands/core.py", line 1705, in get
    return self.execute_command("GET", name)
  File "/usr/lib/python3.10/site-packages/redis/client.py", line 1235, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 1387, in get_connection
    connection.connect()
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 617, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 2 connecting to unix socket: /usr/local/searxng-redis/run/redis.sock. No such file or directory.
[pid: 15|app: 0|req: 11/26] 192.168.178.3 () {50 vars in 1226 bytes} [Mon Nov  7 20:13:58 2022] GET /preferences => generated 265 bytes in 4 msecs (HTTP/1.1 500) 9 headers in 321 bytes (1 switches on core 0)
2022-11-07 20:19:59,012 ERROR:searx.webapp: Exception on /preferences [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 611, in connect
    sock = self.retry.call_with_retry(
  File "/usr/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 612, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 1129, in _connect
    sock.connect(self.path)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/searxng/searx/webapp.py", line 1002, in preferences
    checker_results = checker_get_result()
  File "/usr/local/searxng/searx/search/checker/background.py", line 87, in get_result
    serialized_result: Optional[bytes] = client.get(REDIS_RESULT_KEY)
  File "/usr/lib/python3.10/site-packages/redis/commands/core.py", line 1705, in get
    return self.execute_command("GET", name)
  File "/usr/lib/python3.10/site-packages/redis/client.py", line 1235, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 1387, in get_connection
    connection.connect()
  File "/usr/lib/python3.10/site-packages/redis/connection.py", line 617, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 2 connecting to unix socket: /usr/local/searxng-redis/run/redis.sock. No such file or directory.
[pid: 20|app: 0|req: 16/31] 192.168.178.3 () {50 vars in 1226 bytes} [Mon Nov  7 20:19:59 2022] GET /preferences => generated 265 bytes in 4 msecs (HTTP/1.1 500) 9 headers in 321 bytes (1 switches on core 3)
```

**Comment by dalf** [comment]
I'm not familiar with unraid, I see only an searx package.
How do you deploy SearXNG on unraid?

**Comment by dalf** [comment]
If you don't use the limiter plugin ( = if your instance is not public), you can change your settings.yml.
Add or replace the redis section with:

```yaml
redis:
  url: false
```

**Comment by athlon770** [comment]
@dalf, I just did a search in the UnRaid Apps for searxng and there is already an update (now version 2022.11.07-8f19bdaf).  Unfortunately it still has the same issue...anyway, here is a pic...
![SearXNG](https://user-images.githubusercontent.com/117673957/200420455-06cb01f6-f523-4030-bb63-a30811212889.jpg)

**Comment by dalf** [comment]
* The change described in [this comment](https://github.com/searxng/searxng/issues/1941#issuecomment-1306169985) can fix the crash.
* #1942 should fix the issue without any change to your settings.yml
* However I see in your log that the checker is enabled:
  * The checker requires a Redis instance since https://github.com/searxng/searxng/pull/1856 : uwsgi was creating issues that we can't fix in some distro.
  * you need to set the [redis URL in your settings.yml](https://github.com/searxng/searxng/blob/d3949269a99a62e17d290c42c866661b65fe3119/searx/settings.yml#L81) (for reference, [searxng-docker](https://github.com/searxng/searxng-docker) does that using docker-compose)
  * until you setup a Redis instance, the checker will be disabled.

**Comment by metal3d** [comment]
In my own case, the error happens when I don't have a Redis service running – I installed SearXNG on Kubernetes (with my own helm chart).
Adding a Redis server and changed the settings to point on `redis://...` (with the correct Redis server URL) worked.

**Comment by pacroy9** [comment]
there came another new update to 2022.11.07-d3949269, in the settings.yml I did not change the redis url, use a public instance and I no longer get an error message when accessing the settings. In the Docker log I could not find any error message in this regard either.

**Comment by athlon770** [comment]
Just updated to 2022.11.07-d3949269, as pacroy9 stated, is is resolved across Edge, Chrome (both on PC and Android).

Thanks for the fast work!

Closing as resolved with latest update.
