### ISSUE TITLE
Bug: soundcloud engine

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#1953]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.11.11-3a765113-dirty

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: httpx.HTTPStatusError
  * Percentage: 100
  * Parameters: `('400', 'Bad Request', 'api-v2.soundcloud.com')`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by return42** [comment]
I can reproduce this issue with an empty search string.

- `!soundcloud` --> response a 400 *Bad Request*
- `!soundcloud maceo` --> works

**Comment by ghost** [comment]
> I can reproduce this issue with an empty search string.
> 
> * `!soundcloud` --> response a 400 _Bad Request_
> * `!soundcloud maceo` --> works

I also tried to change url in soundcloud.py, from api-v2.soundcloud.com to api.soundcloud.com (according to  https://developers.soundcloud.com/docs/api/explorer/open-api) but it didn't make any difference, any search fails with the same error.

**Comment by return42** [comment]
Does is mean soundcloud does not work for you even if you use a search term like `!soundcloud maceo` .. is your server public, where I can test it?

**Comment by ghost** [comment]
> Does is mean soundcloud does not work for you even if you use a search term like `!soundcloud maceo` .. is your server public, where I can test it?

Yes, it does not work whatever term I put, but the search works normally from their website. Unfortunately my instance is private, I can paste the whole error log if you want.

**Comment by ghost** [comment]
Unfortunately, even using the docker image I get the same error.. It should be something from my side because soundcloud works if I use any public instance, but I really have no clue on what is happening.

**Comment by return42** [comment]
I'm sorry, I do not have a clue .. Do you have issues when you start an instance by `make run`?

**Comment by ghost** [comment]
@return42 thanks for the reply, now i only have the docker installation but i have noticed that every time i start the instance the soundcloud engine fails to initialize (and now also wikidata). Could it be related to Tor?

**Comment by return42** [comment]
> Could it be related to Tor?

I'm not experienced in a tor setup .. but yes, I assume .. @tiekoetter do you have a clue?

**Comment by ghost** [comment]
Just checked, if I don't use Tor the engine works. Because it looks like there is no fix for now, I will just remove the engine. Closing.

**Comment by rasos** [comment]
I am not using TOR and also had issues to start SearxNG: 

```
2022-12-07 09:47:29,460 ERROR:searx.engines.soundcloud: Fail to initialize
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/anyio/streams/tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "/usr/lib/python3.10/ssl.py", line 917, in read
    v = self._sslobj.read(len)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2548)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 31, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "/usr/lib/python3.10/site-packages/anyio/streams/tls.py", line 195, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "/usr/lib/python3.10/site-packages/anyio/streams/tls.py", line 137, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "/usr/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1265, in receive
    await self._protocol.read_event.wait()
  File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 29, in read
    with anyio.fail_after(timeout):
  File "/usr/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/lib/python3.10/site-packages/httpx/_transports/default.py", line 308, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/lib/python3.10/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/usr/lib/python3.10/site-packages/httpcore/_async/http2.py", line 143, in handle_async_request
    raise exc
  File "/usr/lib/python3.10/site-packages/httpcore/_async/http2.py", line 111, in handle_async_request
    status, headers = await self._receive_response(
  File "/usr/lib/python3.10/site-packages/httpcore/_async/http2.py", line 228, in _receive_response
    event = await self._receive_stream_event(request, stream_id)
  File "/usr/lib/python3.10/site-packages/httpcore/_async/http2.py", line 259, in _receive_stream_event
    await self._receive_events(request, stream_id)
  File "/usr/lib/python3.10/site-packages/httpcore/_async/http2.py", line 278, in _receive_events
    events = await self._read_incoming_data(request)
  File "/usr/lib/python3.10/site-packages/httpcore/_async/http2.py", line 338, in _read_incoming_data
    raise exc
  File "/usr/lib/python3.10/site-packages/httpcore/_async/http2.py", line 324, in _read_incoming_data
    data = await self._network_stream.read(self.READ_NUM_BYTES, timeout)
  File "/usr/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 28, in read
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout
```
When commenting out soundcloud in settings.yml docker started again.

**Comment by ghost** [comment]
@rasos so when you keep soundcloud the instance doesn't even start?

**Comment by rasos** [comment]
@Evhorizon activated soundcloud in settings.yml and all is working again as expected and shows results. It probably throws the exception if their search API can not be reached, as it seemed to be the case earlier today.

**Comment by ghost** [comment]
Nice to hear that, I guess that with Tor enabled their API is never reachable 😁

**Comment by return42** [comment]
> Nice to hear that, I guess that with Tor enabled their API is never reachable 😁

Is this the answer to this issue? .. If so I think we can close this issue (from SearXNG side we can't do anything to improve the behaviour).

**Comment by ghost** [comment]
> > Nice to hear that, I guess that with Tor enabled their API is never reachable 😁
> 
> Is this the answer to this issue? .. If so I think we can close this issue (from SearXNG side we can't do anything to improve the behaviour).

Neither the soundcloud guys have an answer, so I think that this topic is a won't fix. Closing again.
