### ISSUE TITLE
Preferences endpoint returns HTTP 500 when locale is set to ar

### ISSUE THREAD

**Issue by mrpaulblack** [searxng/searxng#2124]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

```
paulgo.io 2023.01.21+674dae94
searx.tiekoetter.com 2023.1.22+a8eb9d15 (93e8a02e)
``` 

**How did you install SearXNG?**
Using public instances and testing locally with latest master.

**How To Reproduce**
* open any SearXNG instance.
* Navigate to the `/preferences` page.
* Select the `USER INTERFACE` tab and set the interface language to `العربية (Arabic)`.
* Press the save button at the bottom of the page.
* Navigate to the `/preferences` page.

**Actual behavior**
[EDIT] problem is the `locale=ar` cookie send with the request. With the value `en` or `de` it works just fine.
There is a unhandled exception thrown on the backend with the following stack trace:
```
DEBUG   searx.webapp                  : http%3A//127.0.0.1%3A8888/preferences uses locale `ar`
INFO    werkzeug                      : 127.0.0.1 - - [23/Jan/2023 21:52:17] "GET /preferences HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/local/code/external/searxng/local/py3/lib64/python3.11/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/code/external/searxng/searx/flaskfix.py", line 71, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/code/external/searxng/local/py3/lib64/python3.11/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/code/external/searxng/local/py3/lib64/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/code/external/searxng/local/py3/lib64/python3.11/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/code/external/searxng/local/py3/lib64/python3.11/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/code/external/searxng/local/py3/lib64/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/code/external/searxng/local/py3/lib64/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/code/external/searxng/searx/webapp.py", line 1073, in preferences
    answerers = [
                ^
  File "/home/local/code/external/searxng/searx/webapp.py", line 1074, in <listcomp>
    {'info': a.self_info(), 'keywords': a.keywords}
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/local/code/external/searxng/searx/answerers/statistics/answerer.py", line 48, in self_info
    'description': gettext('Compute {functions} of the arguments').format(functions='/'.join(keywords)),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'العملية'
```
=> Seems to only happen with this language; I did send the following cookies with the request to the `/preferences` endpoint:
```
Cookie: categories=general; language=en-US; locale=ar; autocomplete=; image_proxy=0; method=POST; safesearch=0; theme=simple; results_on_new_tab=0; doi_resolver=oadoi.org; simple_style=auto; center_alignment=0; query_in_title=0; infinite_scroll=0; disabled_engines=; enabled_engines=; disabled_plugins=; enabled_plugins=; tokens=; maintab=on; enginetab=on
```

**Expected behavior**
The preferences page opens again. The user can make changes to settings and save them.

**Screenshots & Logs**

**Additional context**

**Comment by return42** [comment]
Its my fault, I accepted the translation of a keyword:

- https://translate.codeberg.org/translate/searxng/searxng/ar/?offset=1&q=Compute+%7Bfunctions%7D+of+the+arguments&sort_by=-priority%2Cposition&checksum=

wrong: `حوسبة معطيات ال{العملية}`
fixed: `{functions}حوسبة معطيات ال`

> Seems to only happen with this language

all other translation use the keyword `{functions}`:

- https://translate.codeberg.org/search/searxng/searxng/?offset=1&q=Compute+%7Bfunctions%7D+of+the+arguments&sort_by=-priority%2Cposition&checksum=
