### ISSUE TITLE
fatal exception: ModuleNotFoundError: No module named 'searx.shared'

### ISSUE THREAD

**Issue by Happyfeet01** [searxng/searxng#2208]
With the latest pull, I get this Error and can't use searxng anymore. 

```searxng  | ModuleNotFoundError: No module named 'searx.shared'
searxng  | 2023-02-20 07:36:03,090 CRITICAL:searx.plugins: searx.plugins.limiter: fatal exception
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/local/searxng/searx/plugins/__init__.py", line 116, in load_plugin
searxng  |     plugin = import_module(plugin_module_name)
searxng  |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
searxng  |     return _bootstrap._gcd_import(name[level:], package, level)
searxng  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
searxng  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
searxng  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
searxng  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
searxng  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
searxng  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
searxng  |   File "/usr/local/searxng/searx/plugins/limiter.py", line 20, in <module>
searxng  |     from searx.shared import redisdb
searxng  | ModuleNotFoundError: No module named 'searx.shared'
Xsearxng  | DAMN ! worker 1 (pid: 1358) died :( trying respawn ...
searxng  | Respawned uWSGI worker 1 (new pid: 1526)
searxng  | DAMN ! worker 2 (pid: 1361) died :( trying respawn ...
searxng  | Respawned uWSGI worker 2 (new pid: 1529)
```

**Comment by return42** [comment]
> With the latest pull

Please fill out the form .. at least we need to know your installation method and how you updated (aka *latest pull*).



**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

**How did you install SearXNG?**

**What happened?**


**How To Reproduce**


**Expected behavior**


**Screenshots & Logs**


**Additional context**

**Comment by return42** [comment]
Closed due lack of feedback.
