### ISSUE TITLE
Search for Laminas\XmlRpc\Client

### ISSUE THREAD

**Issue by r0073rr0r** [searxng/searxng#2250]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**
Try searching for:  Laminas\XmlRpc\Client

Search Laminas\XmlRpc\Client
**Expected behavior**

**Screenshots & Logs**

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
**Additional context**

**Comment by Solirs** [comment]
Tested and can confirm from latest commit
Full error:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.10/sre_parse.py", line 1051, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\X'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Solirs/Documents/code/searxng/local/py3/lib64/python3.10/site-packages/flask/app.py", line 2551, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/Solirs/Documents/code/searxng/searx/flaskfix.py", line 71, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/Solirs/Documents/code/searxng/local/py3/lib64/python3.10/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/home/Solirs/Documents/code/searxng/local/py3/lib64/python3.10/site-packages/flask/app.py", line 2531, in wsgi_app
    response = self.handle_exception(e)
  File "/home/Solirs/Documents/code/searxng/local/py3/lib64/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Solirs/Documents/code/searxng/local/py3/lib64/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Solirs/Documents/code/searxng/local/py3/lib64/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Solirs/Documents/code/searxng/local/py3/lib64/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/Solirs/Documents/code/searxng/searx/webapp.py", line 716, in search
    result['content'] = highlight_content(escape(result['content'][:1024]), search_query.query)
  File "/home/Solirs/Documents/code/searxng/searx/webutils.py", line 177, in highlight_content
    content = re.sub(regex_highlight_cjk(q), f'<span class="highlight">{q}</span>', content)
  File "/usr/lib64/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib64/python3.10/re.py", line 326, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib64/python3.10/re.py", line 317, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/lib64/python3.10/sre_parse.py", line 1054, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \X at position 31
```

**Comment by return42** [comment]
fixed in https://github.com/searxng/searxng/pull/2257
