### ISSUE TITLE
searxng can't search for anything ending by \xff or \x00

### ISSUE THREAD

**Issue by nyuware** [searxng/searxng#2415]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

```
2023.2.20+d669da81 (i need to upgrade)
``` 

**What happened?**
if you search for the ```\xff``` or ```\x00```, searx reports a 502 error 

**How To Reproduce**
just search  ```\xff``` or ```\x00```
https://searx.nyuware.pw/search?q=%5Cxff
https://searx.nyuware.pw/search?q=%5Cx00

**Expected behavior**
search for the entered values 

**Screenshots & Logs**
![image](https://github.com/searxng/searxng/assets/48033818/20edbf0e-ae65-4abe-ad90-4d18e5f9ecbf)
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/searxng/searx/webapp.py", line 715, in search
    result['content'] = highlight_content(escape(result['content'][:1024]), search_query.query)
  File "/usr/local/searxng/searx/webutils.py", line 177, in highlight_content
    content = re.sub(regex_highlight_cjk(q), f'<span class="highlight">{q}</span>', content)
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.10/re.py", line 326, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python3.10/re.py", line 317, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/lib/python3.10/sre_parse.py", line 1054, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \x at position 24
[pid: 11|app: 0|req: 307/343] 172.18.0.1 () {56 vars in 1081 bytes} [Wed May 10 13:51:27 2023] GET /search?q=%5Cx00 => generated 265 bytes in 731 msecs (HTTP/1.1 500) 9 headers in 550 bytes (1 switches on core 3)```



Kind of a weird bug, not really important but was funny to find that out

**Comment by return42** [comment]
This issue has been fixed ..

> 2023.2.20+d669da81 (i need to upgrade)

Yes, please update and the issue is solved .. 

- https://github.com/searxng/searxng/pull/2257
- https://github.com/searxng/searxng/issues/2250
- https://github.com/searxng/searxng/issues/2256
