### ISSUE TITLE
Qwant api Error 

### ISSUE THREAD

**Issue by hivefi** [searxng/searxng#2441]
Version: 2023.5.15+50cd7e2b
-->
**How did you install SearXNG?**
https://github.com/searxng/searxng-docker

**How To Reproduce**
just any search

**Expected behavior**
No error 

**Screenshots & Logs**
N/A

**Additional context**
N/A

`**Browser:**`
Errors and exceptions
Exception | searx.exceptions.SearxEngineAPIException | Percentage | 100
-- | -- | -- | --
API error::unknown
searx/engines/qwant.py:129
response
raise SearxEngineAPIException('API error::' + msg)

**Server**
`File "/usr/local/searxng/searx/engines/qwant.py", line 129, in response
    raise SearxEngineAPIException('API error::' + msg)
searx.exceptions.SearxEngineAPIException: API error::unknown
2023-05-17 11:59:52,755 WARNING:searx.engines.qwant: ErrorContext('searx/engines/qwant.py', 129, "raise SearxEngineAPIException('API error::' + msg)", 'searx.exceptions.SearxEngineAPIException', None, ('API error::unknown',)) False
2023-05-17 11:59:52,757 ERROR:searx.engines.qwant: exception : API error::unknown
Traceback (most recent call last):
  File "/usr/local/searxng/searx/search/processors/online.py", line 165, in search
    search_results = self._search_basic(query, params)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/search/processors/online.py", line 153, in _search_basic
    return self.engine.response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/engines/qwant.py", line 129, in response
    raise SearxEngineAPIException('API error::' + msg)
searx.exceptions.SearxEngineAPIException: API error::unknown
`

**Comment by return42** [comment]
I close this in  favor of the other issue https://github.com/searxng/searxng/issues/2440 which 1min reported before this one :-)
