### ISSUE TITLE
Redis error for first time installing on Arch Linux...

### ISSUE THREAD

**Issue by GabubuAvailable** [searxng/searxng#2564]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
```shell
(searx-pyenv) [searxng@bread-AMDPC searxng-src]$ git log -1
commit a446dea1bb492eac417de9a900fae7cdf94aeec0 (HEAD -> master, origin/master, origin/HEAD)
Merge: 4380fc2b b4773498
...
``` 
**How did you install SearXNG?**
Followed the "Step-by-step" guide for Arch Linux
https://docs.searxng.org/admin/installation-searxng.html#installation-basic

**What happened?**
Um... I just installed and when I used the `python searx/webapp.py` command, I've got that python "spaghetti" in which I mentioned in `Screenshots & Logs` section...

**How To Reproduce**
Idk how but all I did was to install it...

**Expected behavior**
Run the script without errors duh...

**Screenshots & Logs**
```python
(searx-pyenv) [searxng@bread-AMDPC searxng-src]$ python searx/webapp.py
2023-07-20 18:14:29,223 ERROR:searx.redisdb: [searxng (969)] can't connect redis DB ...
Traceback (most recent call last):
  File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/redis/connection.py", line 707, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/redis/connection.py", line 708, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/redis/connection.py", line 1191, in _connect
    sock.connect(self.path)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/searxng/searxng-src/searx/redisdb.py", line 56, in initialize
    _CLIENT.ping()
  File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/redis/commands/core.py", line 1205, in ping
    return self.execute_command("PING", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/redis/connection.py", line 1461, in get_connection
    connection.connect()
  File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/redis/connection.py", line 713, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 2 connecting to unix socket: /usr/local/searxng-redis/run/redis.sock. No such file or directory.
2023-07-20 18:14:29,316 ERROR:searx.plugins.limiter: The limiter requires Redis
 * Serving Flask app 'webapp'
 * Debug mode: off
``` 

**Additional context**
no

**Comment by return42** [comment]
> Followed the "Step-by-step" guide for Arch Linux

I assume you C&P the `settings.yml`:

![image](https://github.com/searxng/searxng/assets/554536/7c598937-264a-4594-8f79-d1ac0cb04a25)

If you do not have a redis DB available, remove this setting from you `settings.yml`.

See: https://docs.searxng.org/admin/settings/settings_redis.html#settings-redis

**Comment by GabubuAvailable** [comment]
Yep! That worked! Thank you so much!
