### ISSUE TITLE
Can reproduce on a private instance (no public access, login needed to access searxng).

### ISSUE THREAD

**Issue by freeload101** [searxng/searxng#2903]
* private instance
* ddg work's fine from the server directly no captcha challenge
* I sware the string that broke it was searching ```!ddg trojan twitter``` 
* killed the docker image and waited 24hrs or so

Reference : https://github.com/searxng/searxng/issues/2796 
```

DEBUG   searx.network.qwant           : HTTP Request: GET https://api.qwant.com/v3/search/web?q=docker+show+logs&locale=en_US&safesearch=0&count=10&offset=0 "HTTP/2 403 Forbidden" (application/json; charset=utf-8)
WARNING searx.engines.qwant           : ErrorContext('searx/engines/qwant.py', 190, 'raise SearxEngineTooManyRequestsException()', 'searx.exceptions.SearxEngineTooManyRequestsException', None, ('Too many request',)) False
DEBUG   searx.searx.search.processor  : Suspend for 3600 seconds
ERROR   searx.engines.qwant           : Too many requests
Traceback (most recent call last):
  File "/usr/local/searxng/searx/search/processors/online.py", line 165, in search
    search_results = self._search_basic(query, params)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/search/processors/online.py", line 153, in _search_basic
    return self.engine.response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/engines/qwant.py", line 152, in response
    return parse_web_api(resp)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/engines/qwant.py", line 190, in parse_web_api
    raise SearxEngineTooManyRequestsException()
searx.exceptions.SearxEngineTooManyRequestsException: Too many request, suspended_time=3600
DEBUG   searx.network.google          : HTTP Request: GET https://www.google.com/search?q=docker+show+logs&hl=en-US&lr=lang_en&cr=countryUS&ie=utf8&oe=utf8&filter=0&start=0&asearch=arc&async=use_ac%3Atrue%2C_fmt%3Aprog "HTTP/2 200 OK" (text/plain; charset=UTF-8)
DEBUG   searx.network.brave           : HTTP Request: GET https://search.brave.com/search?q=docker+show+logs "HTTP/2 200 OK" (text/html; charset=utf-8)
DEBUG   searx.engines.google          : data:image objects --> []
DEBUG   searx.network.duckduckgo      : HTTP Request: GET https://lite.duckduckgo.com/lite/?q=docker+show+logs "HTTP/2 200 OK" (text/html; charset=UTF-8)
DEBUG   searx.engines.duckduckgo      : new vqd value: 4-118203438981990546468469855625203390181
DEBUG   searx.engines.duckduckgo      : param data: {'q': 'docker show logs', 'vqd': '4-118203438981990546468469855625203390181', 'kl': 'us-en', 'df': ''}
DEBUG   searx.engines.duckduckgo      : param cookies: {'kl': 'us-en'}
DEBUG   searx.network.duckduckgo      : HTTP Request: POST https://lite.duckduckgo.com/lite/ "HTTP/2 403 Forbidden" (text/html; charset=UTF-8)
WARNING searx.engines.duckduckgo      : ErrorContext('searx/search/processors/online.py', 118, "response = req(params['url'], **request_args)", 'searx.exceptions.SearxEngineAccessDeniedException', None, ('HTTP error 403',)) False
DEBUG   searx.searx.search.processor  : Suspend for 86400 seconds
ERROR   searx.engines.duckduckgo      : Searx is blocked

```

working localy fine 

```
 links -dump "https://duckduckgo.com/?q=panda" | sort | uniq -c | sort -nr | head -n 10
     29
     12
      7
      2    _________________________________________ [ Search ]
      1      you, Panda has 22 stores in Quebec and an online shop.
      1      years. Visit Panda online or in store today.
      1      www.wwf.org.uk/learn/fascinating-facts/pandas
      1      www.worldwildlife.org/species/giant-panda
      1      www.spin.com/2023/10/paramore-re-this-is-why-remix-album/
      1      www.pbs.org/wnet/nature/blog/panda-fact-sheet/
root@debian:/opt# links -dump "https://duckduckgo.com/?q=panda" | sort | uniq -c | sort -nr | head -n 30
     28
     12
      7
      2    _________________________________________ [ Search ]
      1      Zoo's panda era comes amid what veteran China-watchers say is a larger trend.
      1      Zoo — and that loan agreement expires late next year. Wilder said the Chinese possibly could be ...
      1      year. The departure of the National Zoo's bears would mean that the only giant pandas left in America are at the Atlanta
      1      www.youtube.com/watch?v=E5ONTXHS2mM
      1      www.youtube.com/watch?v=5ylh5F4ol28
      1      www.youtube.com/watch?v=4NJlUribp3c
      1      www.tdplace.ca/event/2023-panda-game/
      1      www.spin.com/2023/10/paramore-re-this-is-why-remix-album/
      1      www.pandaexpress.com
      1      www.pandaexpress.ca/en/Menu
      1      www.pandabuy.com
      1      www.nationalgeographic.com/animals/mammals/facts/giant-panda
      1      www.latimes.com/world-nation/story/2023-10-03/pandas-could-be-gone-from-americas-zoos-by-the-end-of-next-year
      1      www.imdb.com/title/tt21692408/
      1      www.ctvnews.ca/world/panda-diplomacy-the-departure-of-d-c-s-beloved-pandas-may-signal-a-wider-chinese-pullback-1.6586369
      1      www.cbc.ca/news/canada/ottawa/panda-game-returns-2023-ottawa-carleton-fotball-1.6719789
      1      www.cbc.ca/news/canada/ottawa/panda-game-2023-sandy-hill-resident-student-party-1.6979881
      1      www.cbc.ca/kidsnews/post/giant-pandas-no-longer-endangered-china-says
      1      www.britannica.com/animal/red-panda
      1      www.britannica.com/animal/giant-panda
      1      www.bloomberg.com/news/articles/2023-09-27/china-taking-back-us-pandas-shows-political-tension    2023-09-27
      1      www.aljazeera.com/news/2023/10/3/what-is-panda-diplomacy-and-why-are-the-bears-going-back-to
      1      wwf.panda.org/discover/knowledge_hub/endangered_species/giant_panda/
      1      wwf.ca/species/giant-pandas/
      1      worldwide. Learn more about the giant panda in this article.
g appearance that has endeared it to people
```

**Comment by return42** [comment]
Not sure for what this issue was opened .. the title and the ref makes me think its related to https://github.com/searxng/searxng/issues/2796, so why is it not posted there .. but in the C&P I see a exception coming from qwant .. IDK / I close this issue.
