### ISSUE TITLE
petal_images broken? discontinued?

### ISSUE THREAD

**Issue by zaggynl** [searxng/searxng#2920]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

**How did you install SearXNG?**

**What happened?**
docker container starts but shows python errors

**How To Reproduce**
clone from git and run with docker start

**Expected behavior**

**Screenshots & Logs**
```
The below shows after starting searxng via docker:
2023-10-09 10:03:20,463 ERROR:searx.engines: Cannot load engine "petal_images"
Traceback (most recent call last):
  File "/usr/local/searxng/searx/engines/__init__.py", line 122, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/utils.py", line 405, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/searxng/searx/engines/petal_images.py'
2023-10-09 10:03:20,463 ERROR:searx.engines: Cannot load engine "petal_images"
Traceback (most recent call last):
  File "/usr/local/searxng/searx/engines/__init__.py", line 122, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/utils.py", line 405, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/searxng/searx/engines/petal_images.py'
2023-10-09 10:03:20,463 ERROR:searx.engines: Cannot load engine "petal_images"
Traceback (most recent call last):
  File "/usr/local/searxng/searx/engines/__init__.py", line 122, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/utils.py", line 405, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data

```

**Additional context**
petalsearch.com appears to no longer exist
per https://en.wikipedia.org/wiki/Petal_Search: 
`It originally had an independent search engine under the same name available on the web, but it was quietly discontinued on June 25th, 2023.`

**Comment by return42** [comment]
Petal engine has been removed:

- https://github.com/searxng/searxng/pull/2614

Drop the engine from your `/etc/searxng/settings.yml`
