### ISSUE TITLE
`make test.unit` fails with `KeyError: ('engine', 'dummy engine', 'search', 'count', 'sent')`

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#2988]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

Last commit of the master branch 96ccec1aa6507ef4d3dc05a08e01187f80080972

**How did you install SearXNG?**
N/A

**How To Reproduce**
`make test.unit`

Output:
```
  File "/home/alexandre/code/searxng/searx/metrics/models.py", line 146, in get
    return self.counters[args]
           ~~~~~~~~~~~~~^^^^^^
KeyError: ('engine', 'dummy engine', 'search', 'count', 'sent')
```

<details>

<summary>full log</summary>

```
BUILDENV  INFO    searx                         : load the default settings from /home/alexandre/code/searxng/searx/settings.yml
BUILDENV  INFO    searx                         : max_request_timeout=None
BUILDENV  INFO    searx                         : version: 2023.5.10+fe0cce2ad+dirty
BUILDENV  build utils/brand.env (settings from: /home/alexandre/code/searxng/etc/settings.yml)
....WARNING searx.botdetection.config     : missing config file: /etc/searxng/limiter.toml
.........................................................................................EE..........E.E..........E..............................................
======================================================================
ERROR: test_browser_empty_locale (tests.unit.test_webapp.ViewsTestCase.test_browser_empty_locale)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alexandre/code/searxng/tests/unit/test_webapp.py", line 219, in test_browser_empty_locale
    result = self.app.get('/preferences', headers={'Accept-Language': ''})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 1160, in get
    return self.open(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/testing.py", line 232, in open
    response = super().open(
               ^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 1114, in open
    response = self.run_wsgi_app(request.environ, buffered=buffered)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 986, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 1262, in run_wsgi_app
    app_rv = app(environ, start_response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/searx/flaskfix.py", line 71, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
    return self.app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/searx/webapp.py", line 913, in preferences
    h = histogram('engine', e.name, 'time', 'total')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/searx/metrics/__init__.py", line 56, in histogram
    raise ValueError("histogram " + repr((*args,)) + " doesn't not exist")
ValueError: histogram ('engine', 'dummy engine', 'time', 'total') doesn't not exist

======================================================================
ERROR: test_browser_locale (tests.unit.test_webapp.ViewsTestCase.test_browser_locale)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alexandre/code/searxng/tests/unit/test_webapp.py", line 205, in test_browser_locale
    result = self.app.get('/preferences', headers={'Accept-Language': 'zh-tw;q=0.8'})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 1160, in get
    return self.open(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/testing.py", line 232, in open
    response = super().open(
               ^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 1114, in open
    response = self.run_wsgi_app(request.environ, buffered=buffered)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 986, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 1262, in run_wsgi_app
    app_rv = app(environ, start_response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/searx/flaskfix.py", line 71, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
    return self.app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/searx/webapp.py", line 913, in preferences
    h = histogram('engine', e.name, 'time', 'total')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/searx/metrics/__init__.py", line 56, in histogram
    raise ValueError("histogram " + repr((*args,)) + " doesn't not exist")
ValueError: histogram ('engine', 'dummy engine', 'time', 'total') doesn't not exist

======================================================================
ERROR: test_locale_occitan (tests.unit.test_webapp.ViewsTestCase.test_locale_occitan)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alexandre/code/searxng/tests/unit/test_webapp.py", line 226, in test_locale_occitan
    result = self.app.get('/preferences?locale=oc')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 1160, in get
    return self.open(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/testing.py", line 232, in open
    response = super().open(
               ^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 1114, in open
    response = self.run_wsgi_app(request.environ, buffered=buffered)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 986, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 1262, in run_wsgi_app
    app_rv = app(environ, start_response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/searx/flaskfix.py", line 71, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
    return self.app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/searx/webapp.py", line 913, in preferences
    h = histogram('engine', e.name, 'time', 'total')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/searx/metrics/__init__.py", line 56, in histogram
    raise ValueError("histogram " + repr((*args,)) + " doesn't not exist")
ValueError: histogram ('engine', 'dummy engine', 'time', 'total') doesn't not exist

======================================================================
ERROR: test_preferences (tests.unit.test_webapp.ViewsTestCase.test_preferences)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alexandre/code/searxng/tests/unit/test_webapp.py", line 198, in test_preferences
    result = self.app.get('/preferences')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 1160, in get
    return self.open(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/testing.py", line 232, in open
    response = super().open(
               ^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 1114, in open
    response = self.run_wsgi_app(request.environ, buffered=buffered)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 986, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 1262, in run_wsgi_app
    app_rv = app(environ, start_response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/searx/flaskfix.py", line 71, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
    return self.app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/searx/webapp.py", line 913, in preferences
    h = histogram('engine', e.name, 'time', 'total')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/searx/metrics/__init__.py", line 56, in histogram
    raise ValueError("histogram " + repr((*args,)) + " doesn't not exist")
ValueError: histogram ('engine', 'dummy engine', 'time', 'total') doesn't not exist

======================================================================
ERROR: test_stats (tests.unit.test_webapp.ViewsTestCase.test_stats)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alexandre/code/searxng/tests/unit/test_webapp.py", line 233, in test_stats
    result = self.app.get('/stats')
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 1160, in get
    return self.open(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/testing.py", line 232, in open
    response = super().open(
               ^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 1114, in open
    response = self.run_wsgi_app(request.environ, buffered=buffered)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 986, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/test.py", line 1262, in run_wsgi_app
    app_rv = app(environ, start_response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/searx/flaskfix.py", line 71, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
    return self.app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/local/py3/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/searx/webapp.py", line 1146, in stats
    engine_stats = get_engines_stats(filtered_engines)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/searx/metrics/__init__.py", line 183, in get_engines_stats
    sent_count = counter('engine', engine_name, 'search', 'count', 'sent')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/searx/metrics/__init__.py", line 69, in counter
    return counter_storage.get(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexandre/code/searxng/searx/metrics/models.py", line 146, in get
    return self.counters[args]
           ~~~~~~~~~~~~~^^^^^^
KeyError: ('engine', 'dummy engine', 'search', 'count', 'sent')

----------------------------------------------------------------------
Ran 165 tests in 1.767s
```

</details>

**Expected behavior**

The unit tests should pass.

**Additional context**

I has this error since one or two months on my computer.
Strangely, nobody had the issue: 
* `make test.unit` fails on my computer with the error above (master branch or any other branches).
* commit
* the CI pass,  nobody has the issue

I have tried various Python versions, reset the virtualenv, etc: nothing fixes the issue, checked the environment variables.

Nobody had the issue until today: https://github.com/searxng/searxng/actions/runs/6753671288
The CI for the searx.network now raises the same issue, unrelated to the PR.

**Comment by return42** [comment]
> The CI for the searx.network now raises the same issue, unrelated to the PR.

Sure? .. In my last PR 

- https://github.com/searxng/searxng/pull/2991

the CI does not fall into this issue.  What Python version do have?

----

Testing python versions ..

In branch of PR https://github.com/searxng/searxng/pull/2685 .. and with runtime management described in #2991 I tried to test in python 3.11.6 :
    
    $ git checkout -b searx_network_rework dalf/searx_network_rework
    Branch 'searx_network_rework' set up to track remote branch 'searx_network_rework' from 'dalf'.
    Switched to a new branch 'searx_network_rework'

    $ echo "python 3.11.6" > .tool-versions
    $ asdf install
    python 3.11.6 is already installed
    
    $ which python
    ~/.asdf/shims/python
    $ python --version
    Python 3.11.6

    $ make clean test.unit
    ...

Not sure what Python 3.11.x version the CI uses / AFAIK we use `actions/setup-python@v4` :

https://github.com/searxng/searxng/blob/96ccec1aa6507ef4d3dc05a08e01187f80080972/.github/workflows/integration.yml#L27-L31

https://github.com/actions/python-versions/blob/e642abaef814f4d4a6bfe1741f814e08dbbc2484/versions-manifest.json#L729-L732

**Comment by dalf** [comment]
I can reproduce the error on the master branch on my computer.

I just try git bisect on the master branch: the error appears on commit 733b795d5327a1be133365d9d46c41d709719109
At least I can reproduce the error on this commit, and not on the previous one.

**[EDIT]** If I comment out these lines https://github.com/searxng/searxng/blob/733b795d5327a1be133365d9d46c41d709719109/tests/unit/test_search.py#L46-L50 the tests in `test_webapp.py` pass (and obviously not the tests in `test_search.py`).

**Comment by dalf** [comment]
So, I confirm the error I get comes from these lines:
https://github.com/searxng/searxng/blob/733b795d5327a1be133365d9d46c41d709719109/tests/unit/test_search.py#L46-L50

One way to fix the errors:

```python
    def setUp(self):
        def dummy(func):
            return func

        self.setattr4test(searx.search, 'copy_current_request_context', dummy)
```

With this fix, we can see that `searx.search` is still mostly standalone = not linked the Flask app (except for the translations).

Now let's put aside the error: according to the [Flask documentation](https://flask.palletsprojects.com/en/2.3.x/testing/), there is some configuration to do to use a Flask app during the tests. This is what is done here (at least for `webapp.app.test_client() `) :
https://github.com/searxng/searxng/blob/96ccec1aa6507ef4d3dc05a08e01187f80080972/tests/unit/test_webapp.py#L16-L30

I've tried to do that in `test_search.py` but it does work, I guess there are too many global variables, and the app can only be initialize once in `test_webapp.py`.

**Comment by return42** [comment]
> The CI for the searx.network now raises the same issue, unrelated to the PR.

Not sure why, but since last rebase the issue no longer raised in the CI of https://github.com/searxng/searxng/pull/2685

**Comment by dalf** [comment]
The issue still exists: https://github.com/searxng/searxng/actions/runs/9903920125/job/27368127534

**Comment by return42** [comment]
In the past, I had the impression that the tests were not always carried out in the same order.   Since some tests perform initializations, these then affect the following tests ... it is not always clear which initializations are used to perform a particular test.  The PR:

- https://github.com/searxng/searxng/pull/3609

is one example.

Is there a way we can control the order unit tests are executed?

**Comment by return42** [comment]
> I just try git bisect on the master branch: the error appears on commit [733b795](https://github.com/searxng/searxng/commit/733b795d5327a1be133365d9d46c41d709719109)

@dalf Not sure but I guess the `dummy engine` in 

``KeyError: ('engine', 'dummy engine', 'search', 'count', 'sent'``

comes from ..

https://github.com/searxng/searxng/blob/733b795d5327a1be133365d9d46c41d709719109/tests/unit/test_query.py#L7-L16

https://github.com/searxng/searxng/blob/733b795d5327a1be133365d9d46c41d709719109/tests/unit/test_query.py#L241-L247

When this Bang tests run before the `test_webapp` runs, we got the key errors since the histogram

```
ERROR: test_preferences (tests.unit.test_webapp.ViewsTestCase.test_preferences)
--> ValueError: histogram ('engine', 'dummy engine', 'time', 'total') doesn't not exist
```

does not contain an entry for the `dummy engine` .. same with the 

```
ERROR: test_stats (tests.unit.test_webapp.ViewsTestCase.test_stats)
--> KeyError: ('engine', 'dummy engine', 'search', 'count', 'sent')
```

So I guess this issue is not related to the 

https://github.com/searxng/searxng/blob/733b795d5327a1be133365d9d46c41d709719109/tests/unit/test_search.py#L46-L50

as you mentioned .. I think the problem is, that we do not unregister the TEST_ENGINES after the test that use the TEST_ENGINES is ended .. the problem is, that we have such a lot of globals ..

https://github.com/searxng/searxng/blob/ef103ba80a8494d01c6dc8ce8e408957d4424b0b/searx/engines/__init__.py#L56

BTW three weeks ago we added another test that loads a `dummy engine` (see https://github.com/searxng/searxng/pull/3559) .. This would also explain why we have been encountering this error more frequently in recent weeks.

**Comment by return42** [comment]
> I think the problem is, that we do not unregister the TEST_ENGINES after the test that use the TEST_ENGINES is ended .

and now I can verify it by the patch below .. and the solution is to unload the TEST_ENGINES in the tearDown process of the bang test .. as done in:

- https://github.com/searxng/searxng/pull/3654 

```diff
diff --git a/tests/unit/test_webapp.py b/tests/unit/test_webapp.py
index 868645e17..6aa1a97d3 100644
--- a/tests/unit/test_webapp.py
+++ b/tests/unit/test_webapp.py
@@ -9,11 +9,25 @@ from searx.results import Timing
 import searx.search.processors
 from searx.search import Search
 from searx.preferences import Preferences
+from searx.engines import load_engines
+
 from tests import SearxTestCase
 
+TEST_ENGINE_NAME = 'dummy engine'
+TEST_ENGINE = {
+    'name': TEST_ENGINE_NAME,
+    'engine': 'dummy',
+    'categories': 'general',
+    'shortcut': 'du',
+    'timeout': 3.0,
+    'tokens': [],
+}
+
 
 class ViewsTestCase(SearxTestCase):  # pylint: disable=missing-class-docstring, too-many-public-methods
     def setUp(self):
+        load_engines([TEST_ENGINE])
+
         # skip init function (no external HTTP request)
         def dummy(*args, **kwargs):  # pylint: disable=unused-argument
             pass
```
