### ISSUE TITLE
Bug: startpage engine / captcha

### ISSUE THREAD

**Issue by un99known99** [searxng/searxng#2989]
maybe related to:  Built-in CAPTCHA solver #2844 

**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.11.3+96ccec1aa

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineCaptchaException
  * Percentage: 100
  * Parameters: `('get_sc_code: [PR-695] query new sc time-stamp failed! (https://www.startpage.com/?sc=)',)`
  * File name: `searx/engines/startpage.py:231`
  * Function: `get_sc_code`
  * Code: `raise SearxEngineCaptchaException(`

**Comment by return42** [comment]
> maybe related to: Built-in CAPTCHA solver https://github.com/searxng/searxng/issues/2844

It will take it time before we will have a "Built-in CAPTCHA sovler". In the interim - as a workaround - you can [answer a CAPTCHA](https://docs.searxng.org/admin/answer-captcha.html) from the server’s IP.

**Comment by Damaj301damaj-lol** [comment]
> > maybe related to: Built-in CAPTCHA solver https://github.com/searxng/searxng/issues/2844
> 
> It will take it time before we will have a "Built-in CAPTCHA sovler". In the interim - as a workaround - you can [answer a CAPTCHA](https://docs.searxng.org/admin/answer-captcha.html) from the server’s IP.

Seems like startpage found a way to block searxng, doing a search from the server ip does work without any captchas

**Comment by return42** [comment]
Startpage has not been requesting a CAPTCHA on my IP address for a few weeks now. It may be that they have lowered the threshold ... but I also see that my bot detection works very efficiently ... but maybe both are true and have a positive effect in total

-----

Might not related, but to write it down somewhere .. On my server I see ERROR logs like .. but I don't know from where the ``bi`` should come from:

```
WARNING searx.engines.startpage       : ErrorContext('searx/engines/startpage.py', 199, "locale = babel.Locale.parse(searxng_locale, sep='-')", 'babel.core.UnknownLocaleError', None, ()) False
ERROR   searx.engines.startpage       : exception : unknown locale 'bi'
Traceback (most recent call last):
  File "/usr/local/searxng/searxng-src/searx/search/processors/online.py", line 163, in search
    search_results = self._search_basic(query, params)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searxng-src/searx/search/processors/online.py", line 137, in _search_basic
    self.engine.request(query, params)
  File "/usr/local/searxng/searxng-src/searx/engines/startpage.py", line 254, in request
    return _request_cat_web(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searxng-src/searx/engines/startpage.py", line 270, in _request_cat_web
    'sc': get_sc_code(params['searxng_locale'], params),  # hint: this func needs HTTP headers,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searxng-src/searx/engines/startpage.py", line 199, in get_sc_code
    locale = babel.Locale.parse(searxng_locale, sep='-')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx-pyenv/lib/python3.12/site-packages/babel/core.py", line 406, in parse
    raise UnknownLocaleError(input_id)
babel.core.UnknownLocaleError: unknown locale 'bi'
```
