### ISSUE TITLE
Engine Load Failure: ‘duckduckgo_images’, ‘gigablast’ and others Missing in SearXNG

### ISSUE THREAD

**Issue by juleeho** [searxng/searxng#3146]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

SearXNG version 2024.1.19+047c7a7cf

**How did you install SearXNG?**

Installed via searxng-docker on Debian

**What happened?**

I’m uncertain about the cause, as everything was functioning smoothly until it suddenly wasn’t. I’ve been utilizing a reverse proxy to handle the SSL certificate for our internal network. The issue arose when the SSL certificate stopped serving the searx container. Consequently, I examined the logs and discovered some errors, which are pasted below.

```
⚠️  Check new version /etc/searxng/uwsgi.ini.new to make sure SearXNG is working properly
⚠️  Check new version /etc/searxng/settings.yml.new to make sure SearXNG is working properly
Listen on 0.0.0.0:8080
[uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
[uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
*** Starting uWSGI 2.0.21 (64bit) on [Tue Jan 23 20:11:25 2024] ***
compiled with version: 12.2.1 20220924 on 28 April 2023 21:13:09
os: Linux-5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13)
nodename: 481c21fdb544
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /usr/local/searxng
detected binary path: /usr/sbin/uwsgi
chdir() to /usr/local/searxng/searx/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1390 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
*** Cache "searxngcache" initialized: 11MB (key: 2136 bytes, keys: 4272000 bytes, data: 8192000 bytes, bitmap: 250 bytes) preallocated ***
uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 4
Python version: 3.11.6 (main, Oct  4 2023, 06:22:18) [GCC 12.2.1 20220924]
Python main interpreter initialized at 0x7f2e53841f78
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 362016 bytes (353 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
added /usr/local/searxng/ to pythonpath.
spawned uWSGI master process (pid: 8)
spawned uWSGI worker 1 (pid: 16, cores: 4)
spawned uWSGI worker 2 (pid: 17, cores: 4)
spawned 4 offload threads for uWSGI worker 1
cache sweeper thread enabled
spawned 4 offload threads for uWSGI worker 2
2024-01-23 20:11:29,604 ERROR:searx.engines: Cannot load engine "duckduckgo_images"
Traceback (most recent call last):
  File "/usr/local/searxng/searx/engines/__init__.py", line 123, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/utils.py", line 417, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/searxng/searx/engines/duckduckgo_images.py'
2024-01-23 20:11:29,604 ERROR:searx.engines: Cannot load engine "duckduckgo_images"
Traceback (most recent call last):
  File "/usr/local/searxng/searx/engines/__init__.py", line 123, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/utils.py", line 417, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/searxng/searx/engines/duckduckgo_images.py'
2024-01-23 20:11:29,634 ERROR:searx.engines: Cannot load engine "gigablast"
Traceback (most recent call last):
  File "/usr/local/searxng/searx/engines/__init__.py", line 123, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/utils.py", line 417, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/searxng/searx/engines/gigablast.py'
2024-01-23 20:11:29,636 ERROR:searx.engines: Cannot load engine "gigablast"
Traceback (most recent call last):
  File "/usr/local/searxng/searx/engines/__init__.py", line 123, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/utils.py", line 417, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/searxng/searx/engines/gigablast.py'
2024-01-23 20:11:29,678 ERROR:searx.engines: Cannot load engine "google_play_apps"
Traceback (most recent call last):
  File "/usr/local/searxng/searx/engines/__init__.py", line 123, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/utils.py", line 417, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/searxng/searx/engines/google_play_apps.py'
2024-01-23 20:11:29,680 ERROR:searx.engines: Cannot load engine "google_play_apps"
Traceback (most recent call last):
  File "/usr/local/searxng/searx/engines/__init__.py", line 123, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/utils.py", line 417, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/searxng/searx/engines/google_play_apps.py'
2024-01-23 20:11:29,768 ERROR:searx.engines: Cannot load engine "twitter"
Traceback (most recent call last):
  File "/usr/local/searxng/searx/engines/__init__.py", line 123, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/utils.py", line 417, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/searxng/searx/engines/twitter.py'
2024-01-23 20:11:29,774 ERROR:searx.engines: Cannot load engine "twitter"
Traceback (most recent call last):
  File "/usr/local/searxng/searx/engines/__init__.py", line 123, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/utils.py", line 417, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/searxng/searx/engines/twitter.py'
2024-01-23 20:11:29,834 ERROR:searx.engines: Cannot load engine "petal_images"
Traceback (most recent call last):
  File "/usr/local/searxng/searx/engines/__init__.py", line 123, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/utils.py", line 417, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/searxng/searx/engines/petal_images.py'
2024-01-23 20:11:29,840 ERROR:searx.engines: Cannot load engine "petal_images"
Traceback (most recent call last):
  File "/usr/local/searxng/searx/engines/__init__.py", line 123, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/utils.py", line 417, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/searxng/searx/engines/petal_images.py'
WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x7f2e53841f78 pid: 17 (default app)
WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x7f2e53841f78 pid: 16 (default app)
```

**Additional context**

I’ve deployed the Searx Docker container on the same system where the Umbrel installation resides.

**Comment by juleeho** [comment]
Rebooting the system solved the problem
