### ISSUE TITLE
Bug: google engine

### ISSUE THREAD

**Issue by mahehro** [searxng/searxng#3209]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.2.11+11c0651ef

**How did you install SearXNG?**
Docker Compose on a vps with traefik, Whoogle works 
```
version: "3.7"
services:
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - web
    volumes:
      - /opt/searxng:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searxng.entrypoints=websecure,web"
      - "traefik.http.routers.searxng.rule=Host(MYDOMAIN)"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    env_file:
      - stack.env
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
networks:
  web:
    external: true`
```

**What happened?**
Error! Engines cannot retrieve results:

google ( Suspended: access denied )

**How To Reproduce**
Do a search

**Expected behavior**
View Google results

**Screenshots & Logs**
![Screenshot_20240213_070849_Firefox](https://github.com/searxng/searxng/assets/28053748/d7c51223-ea13-4aa7-916c-bbb51e788606)

```
2024-02-13 06:04:13,244 WARNING:searx.engines.google: ErrorContext('searx/search/processors/online.py', 118, "response = req(params['url'], **request_args)", 'searx.exceptions.SearxEngineAccessDeniedException', None, ('HTTP error 403',)) False
2024-02-13 06:04:13,244 ERROR:searx.engines.google: SearXNG is blocked
Traceback (most recent call last):
  File "/usr/local/searxng/searx/search/processors/online.py", line 165, in search
    search_results = self._search_basic(query, params)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/search/processors/online.py", line 149, in _search_basic
    response = self._send_http_request(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/search/processors/online.py", line 118, in _send_http_request
    response = req(params['url'], **request_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/__init__.py", line 165, in get
    return request('get', url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/__init__.py", line 96, in request
    return future.result(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/searxng/searx/network/network.py", line 291, in request
    return await self.call_client(False, method, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/network.py", line 274, in call_client
    return Network.patch_response(response, do_raise_for_httperror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/network.py", line 247, in patch_response
    raise_for_httperror(response)
  File "/usr/local/searxng/searx/network/raise_for_httperror.py", line 75, in raise_for_httperror
    raise SearxEngineAccessDeniedException(message='HTTP error ' + str(resp.status_code))
searx.exceptions.SearxEngineAccessDeniedException: HTTP error 403, suspended_time=86400
2024-02-13 06:04:33,026 WARNING:searx.engines.google: ErrorContext('searx/search/processors/online.py', 118, "response = req(params['url'], **request_args)", 'searx.exceptions.SearxEngineAccessDeniedException', None, ('HTTP error 403',)) False
2024-02-13 06:04:33,026 ERROR:searx.engines.google: SearXNG is blocked
Traceback (most recent call last):
  File "/usr/local/searxng/searx/search/processors/online.py", line 165, in search
    search_results = self._search_basic(query, params)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/search/processors/online.py", line 149, in _search_basic
    response = self._send_http_request(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/search/processors/online.py", line 118, in _send_http_request
    response = req(params['url'], **request_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/__init__.py", line 165, in get
    return request('get', url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/__init__.py", line 96, in request
    return future.result(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/searxng/searx/network/network.py", line 291, in request
    return await self.call_client(False, method, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/network.py", line 274, in call_client
    return Network.patch_response(response, do_raise_for_httperror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/network.py", line 247, in patch_response
    raise_for_httperror(response)
  File "/usr/local/searxng/searx/network/raise_for_httperror.py", line 75, in raise_for_httperror
    raise SearxEngineAccessDeniedException(message='HTTP error ' + str(resp.status_code))
searx.exceptions.SearxEngineAccessDeniedException: HTTP error 403, suspended_time=86400
2024-02-13 06:06:36,635 ERROR:searx.engines.duckduckgo: engine timeout
2024-02-13 06:06:36,836 WARNING:searx.engines.duckduckgo: ErrorContext('searx/search/processors/online.py', 118, "response = req(params['url'], **request_args)", 'httpx.TimeoutException', None, (None, None, None)) False
2024-02-13 06:06:36,836 ERROR:searx.engines.duckduckgo: HTTP requests timeout (search duration : 3.2014631679994636 s, timeout: 3.0 s) : TimeoutException`
```

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:118`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by mahehro** [comment]
Here is my compose file in a readable form.
![Screenshot_20240213_071642_Firefox](https://github.com/searxng/searxng/assets/28053748/465cc2ad-dda1-4c73-9b8c-ac78352b231b)

**Comment by unixfox** [comment]
Unfortunately your IP address is blocked by Google.

You will have to change it in order to solve this issue.

**Comment by return42** [comment]
Is it only google that is blocked, do other engines work? .. is your instance public?

**Comment by mahehro** [comment]
> Is it only google that is blocked, do other engines work? .. is your instance public?

Only Google. rarely also DuckDuckGo due to timeouts.

**Comment by return42** [comment]
Do you use IPv6 for outgoing requests? 

- https://github.com/searxng/searxng/discussions/3188

**Comment by mahehro** [comment]
IPv4 & IPv6
The server is hosted on Hetzner Cloud.


________________________________

**Comment by return42** [comment]
Use IPv4 for outgoing .. read the answer in the discussion I linked above ..

```
outgoing:
  source_ips: 0.0.0.0
```

**Comment by mahehro** [comment]
It works, thank you! Sorry, I didn't see the link via email.
