### ISSUE TITLE
make search.checker reports trillions of tracebacks

### ISSUE THREAD

**Issue by return42** [searxng/searxng#3310]
With `make search.checker` we can run a check that probes every single engine we have.  And we have added cron job:

- https://github.com/searxng/searxng/pull/3262 

So far so good .. in practice its hard to read checker's output since checker reports trillions of tracebacks.  To verify what I mean run `make search.checker` or have a look at the cron job log:

- https://github.com/searxng/searxng/actions/runs/8198540553/job/22422226537#step:6:1

which ends in

![grafik](https://github.com/searxng/searxng/assets/554536/8b8ee656-1897-46e9-b4f6-757d5d7ae1f4)

May we do not show the full traceback, just one line should be enough .. or we completely suppress these messages that are displayed when loading the images:

```
 File "./local/py3/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./searx/search/checker/impl.py", line 92, in _download_and_check_if_image
    r.close()
```

Related:

- https://github.com/searxng/searxng/issues/3311

**Comment by glanham-jr** [comment]
Just realized you assigned `dalf`, but I have a quick enough implementation that fixes this issue and is backwards compatible.

**Comment by return42** [comment]
superseded by:

- https://github.com/searxng/searxng/pull/5767
