### ISSUE TITLE
The standalone scripts do no longer work

### ISSUE THREAD

**Issue by return42** [searxng/searxng#332]
The _standalone_ scripts do no longer work:: 

```
./manage pyenv.cmd python searx_extra/google_search.py foo
Traceback (most recent call last):
  File "searx_extra/google_search.py", line 10, in <module>
    from searx.search import default_request_params
ImportError: cannot import name 'default_request_params' from 'searx.search' (searx/searx/search/__init__.py)
```

```
/manage pyenv.cmd python searx_extra/standalone_searx.py foo
Traceback (most recent call last):
  File "searx_extra/standalone_searx.py", line 215, in <module>
    sys.stdout.write(dumps(
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
...
  File "searx_extra/standalone_searx.py", line 138, in json_serial
    raise TypeError("Type ({}) not serializable".format(type(obj)))
TypeError: Type (<class 'datetime.timedelta'>) not serializable
```

**Comment by not-my-profile** [comment]
This issue was fixed in #658.
