### ISSUE TITLE
[Bug] New 'Hostnames plugin' not working with yml files

### ISSUE THREAD

**Issue by Sommerwiesel** [searxng/searxng#3557]
Vanilla 2024.6.7+f5eb56b6
Using official docker image

**What happened?**
Trying to change to new 'Hostnames plugin' as described here: https://github.com/searxng/searxng/discussions/3553)
Using a simple config with yml files, plugin fails to load due to an file not found error with the yml file

**How To Reproduce**
Switch to 'Hostnames plugin'
Use example config (and create the appropriate yml file)
Get error FileNotFoundError: File remove-hosts.yml does not exist!

**Expected behavior**
It works and loads the yml file

**Screenshots & Logs**

settings.yml
```shell
hostnames:
  replace: 'replace-hosts.yml'
  remove: 'remove-hosts.yml'
  high_priority:
  low_priority:

```

<details><summary>config files and permissions</summary>
<p>

docker exec -it searxng /bin/sh
/usr/local/searxng # ls -l /etc/searxng/
total 148
-rwxr-xr-x    1 10044    10044         1046 May 24 14:56 limiter.toml
-rwxr-xr-x    1 10044    10044       131003 Jun  7 14:05 remove-hosts.yml
-rwxr-xr-x    1 10044    10044          938 Jun  7 14:01 replace-hosts.yml
-rwxr-xr-x    1 10044    10044         7708 Jun  7 20:11 settings.yml
-rwxr-xr-x    1 10044    10044         1102 May  4 09:53 uwsgi.ini

</p>
</details> 

<details><summary>docker log</summary>
<pre>
2024-06-09 08:07:48,781 ERROR:searx.plugins: searx.plugins.hostnames: exception while loading, the plugin is disabled
Traceback (most recent call last):
  File "/usr/local/searxng/searx/plugins/__init__.py", line 115, in load_plugin
    plugin = import_module(plugin_module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/searxng/searx/plugins/hostnames.py", line 120, in <module>
    replacements = _load_regular_expressions_with_fallback('replace')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/plugins/hostnames.py", line 102, in _load_regular_expressions_with_fallback
    expressions = _load_regular_expressions(settings_key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/plugins/hostnames.py", line 88, in _load_regular_expressions
    setting_value = get_yaml_file(setting_value)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/settings_loader.py", line 37, in get_yaml_file
    raise FileNotFoundError(f"File {file_name} does not exist!")
FileNotFoundError: File replace-hosts.yml does not exist!
2024-06-09 08:07:48,781 ERROR:searx.plugins: searx.plugins.hostnames: exception while loading, the plugin is disabled
Traceback (most recent call last):
  File "/usr/local/searxng/searx/plugins/__init__.py", line 115, in load_plugin
    plugin = import_module(plugin_module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/searxng/searx/plugins/hostnames.py", line 120, in <module>
    replacements = _load_regular_expressions_with_fallback('replace')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/plugins/hostnames.py", line 102, in _load_regular_expressions_with_fallback
    expressions = _load_regular_expressions(settings_key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/plugins/hostnames.py", line 88, in _load_regular_expressions
    setting_value = get_yaml_file(setting_value)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/settings_loader.py", line 37, in get_yaml_file
    raise FileNotFoundError(f"File {file_name} does not exist!")
FileNotFoundError: File replace-hosts.yml does not exist!
2024-06-09 08:07:48,783 ERROR:searx.plugins: searx.plugins.hostnames: exception while loading, the plugin is disabled
Traceback (most recent call last):
  File "/usr/local/searxng/searx/plugins/__init__.py", line 115, in load_plugin
    plugin = import_module(plugin_module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/searxng/searx/plugins/hostnames.py", line 120, in <module>
    replacements = _load_regular_expressions_with_fallback('replace')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/plugins/hostnames.py", line 102, in _load_regular_expressions_with_fallback
    expressions = _load_regular_expressions(settings_key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/plugins/hostnames.py", line 88, in _load_regular_expressions
    setting_value = get_yaml_file(setting_value)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/settings_loader.py", line 37, in get_yaml_file
    raise FileNotFoundError(f"File {file_name} does not exist!")
FileNotFoundError: File replace-hosts.yml does not exist!
2024-06-09 08:07:48,783 ERROR:searx.plugins: searx.plugins.hostnames: exception while loading, the plugin is disabled
Traceback (most recent call last):
  File "/usr/local/searxng/searx/plugins/__init__.py", line 115, in load_plugin
    plugin = import_module(plugin_module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/searxng/searx/plugins/hostnames.py", line 120, in <module>
    replacements = _load_regular_expressions_with_fallback('replace')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/plugins/hostnames.py", line 102, in _load_regular_expressions_with_fallback
    expressions = _load_regular_expressions(settings_key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/plugins/hostnames.py", line 88, in _load_regular_expressions
    setting_value = get_yaml_file(setting_value)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/settings_loader.py", line 37, in get_yaml_file
    raise FileNotFoundError(f"File {file_name} does not exist!")
FileNotFoundError: File replace-hosts.yml does not exist!

</pre>
</details> 

**Additional context**
I triple checked that everything is as it should be, including the yml syntax, file permissions and location of the yml file that causes the FileNotFoundError.

**Comment by return42** [comment]
@Bnyro could it be, that the file is loaded from the wrong path:

https://github.com/searxng/searxng/blob/f5eb56b63f250c7804e5e1cf4426e550bc933906/searx/settings_loader.py#L34-L35

is in the searx folder of the repo, while the *user setting* is in one of:

https://github.com/searxng/searxng/blob/f5eb56b63f250c7804e5e1cf4426e550bc933906/searx/settings_loader.py#L46-L52

**Comment by Sommerwiesel** [comment]
@return42 Can confirm this. Have just temporarly mounted both yml files to /usr/local/searxng/searx and the FileNotFound error is gone

**Comment by return42** [comment]
@Sommerwiesel can you give https://github.com/searxng/searxng/pull/3578 a try?

**Comment by Sommerwiesel** [comment]
@return42 My searXNG instance (prod) uses the official docker image and I don't have the time right now to pull that PR, compile and build my own docker image from it (or setup a separate standalone testing instance). I'm willing to test it but you would have to wait at least 1 week.

**Comment by return42** [comment]
@Sommerwiesel thanks for your feedback ... I just wanted to ask, but I didn't realize how time-consuming it might be for you .. I'm not familiar with the docker toolchain .. I don't use docker (yet) and without docker, the test of a PR is a bit easier ;-)

Don't stress, we'll find someone to test it ... or we'll wait until you have time ... thanks for your support.
