### ISSUE TITLE
Error: 500: 1 validation error for CompletionResponse text none is not an allowed value (type=type_error.none.not_allowed)

### ISSUE THREAD

**Issue by thisaul** [searxng/searxng#3562]
![Screenshot 2024-06-11 at 12 33 40 AM](https://github.com/searxng/searxng/assets/1552108/2cdf3a44-425a-42e6-8e5b-9d428f72b35d)

I used Phi3 Local
Ollama was running at http://127.0.0.1:11434/

Logs from docker:

2024-06-11 00:27:46 backend-1   | INFO:     192.168.65.1:24305 - "POST /chat HTTP/1.1" 200 OK
2024-06-11 00:27:47 backend-1   | Traceback (most recent call last):
2024-06-11 00:27:47 backend-1   |   File "/workspace/src/backend/chat.py", line 111, in stream_qa_objects
2024-06-11 00:27:47 backend-1   |     async for completion in response_gen:
2024-06-11 00:27:47 backend-1   |   File "/workspace/.venv/lib/python3.11/site-packages/llama_index/core/llms/callbacks.py", line 280, in wrapped_gen
2024-06-11 00:27:47 backend-1   |     async for x in f_return_val:
2024-06-11 00:27:47 backend-1   |   File "/workspace/.venv/lib/python3.11/site-packages/llama_index/llms/ollama/base.py", line 410, in gen
2024-06-11 00:27:47 backend-1   |     yield CompletionResponse(
2024-06-11 00:27:47 backend-1   |           ^^^^^^^^^^^^^^^^^^^
2024-06-11 00:27:47 backend-1   |   File "/workspace/.venv/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
2024-06-11 00:27:47 backend-1   |     raise validation_error
2024-06-11 00:27:47 backend-1   | pydantic.v1.error_wrappers.ValidationError: 1 validation error for CompletionResponse
2024-06-11 00:27:47 backend-1   | text
2024-06-11 00:27:47 backend-1   |   none is not an allowed value (type=type_error.none.not_allowed)
2024-06-11 00:27:47 backend-1   | 
2024-06-11 00:27:47 backend-1   | During handling of the above exception, another exception occurred:
2024-06-11 00:27:47 backend-1   | 
2024-06-11 00:27:47 backend-1   | Traceback (most recent call last):
2024-06-11 00:27:47 backend-1   |   File "/workspace/src/backend/main.py", line 97, in generator
2024-06-11 00:27:47 backend-1   |     async for obj in stream_qa_objects(chat_request):
2024-06-11 00:27:47 backend-1   |   File "/workspace/src/backend/chat.py", line 140, in stream_qa_objects
2024-06-11 00:27:47 backend-1   |     raise HTTPException(status_code=500, detail=detail)
2024-06-11 00:27:47 backend-1   | fastapi.exceptions.HTTPException: 500: 1 validation error for CompletionResponse
2024-06-11 00:27:47 backend-1   | text
2024-06-11 00:27:47 backend-1   |   none is not an allowed value (type=type_error.none.not_allowed)
2024-06-11 00:27:47 backend-1   | 
2024-06-11 00:27:47 frontend-1  |  GET / 200 in 65ms
2024-06-11 00:27:47 frontend-1  |  GET /icon.ico?008a98dce61136d3 200 in 13ms
2024-06-11 00:27:48 frontend-1  |  GET /icon.ico?008a98dce61136d3 200 in 17ms
2024-06-11 00:27:48 backend-1   | INFO:     192.168.65.1:19765 - "POST /chat HTTP/1.1" 200 OK
2024-06-11 00:27:50 backend-1   | Traceback (most recent call last):
2024-06-11 00:27:50 backend-1   |   File "/workspace/src/backend/chat.py", line 111, in stream_qa_objects
2024-06-11 00:27:50 backend-1   |     async for completion in response_gen:
2024-06-11 00:27:50 backend-1   |   File "/workspace/.venv/lib/python3.11/site-packages/llama_index/core/llms/callbacks.py", line 280, in wrapped_gen
2024-06-11 00:27:50 backend-1   |     async for x in f_return_val:
2024-06-11 00:27:50 backend-1   |   File "/workspace/.venv/lib/python3.11/site-packages/llama_index/llms/ollama/base.py", line 410, in gen
2024-06-11 00:27:50 backend-1   |     yield CompletionResponse(
2024-06-11 00:27:50 backend-1   |           ^^^^^^^^^^^^^^^^^^^
2024-06-11 00:27:50 backend-1   |   File "/workspace/.venv/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
2024-06-11 00:27:50 backend-1   |     raise validation_error
2024-06-11 00:27:50 backend-1   | pydantic.v1.error_wrappers.ValidationError: 1 validation error for CompletionResponse
2024-06-11 00:27:50 backend-1   | text
2024-06-11 00:27:50 backend-1   |   none is not an allowed value (type=type_error.none.not_allowed)
2024-06-11 00:27:50 backend-1   | 
2024-06-11 00:27:50 backend-1   | During handling of the above exception, another exception occurred:
2024-06-11 00:27:50 backend-1   | 
2024-06-11 00:27:50 backend-1   | Traceback (most recent call last):
2024-06-11 00:27:50 backend-1   |   File "/workspace/src/backend/main.py", line 97, in generator
2024-06-11 00:27:50 backend-1   |     async for obj in stream_qa_objects(chat_request):
2024-06-11 00:27:50 backend-1   |   File "/workspace/src/backend/chat.py", line 140, in stream_qa_objects
2024-06-11 00:27:50 backend-1   |     raise HTTPException(status_code=500, detail=detail)
2024-06-11 00:27:50 backend-1   | fastapi.exceptions.HTTPException: 500: 1 validation error for CompletionResponse
2024-06-11 00:27:50 backend-1   | text
2024-06-11 00:27:50 backend-1   |   none is not an allowed value (type=type_error.none.not_allowed)
2024-06-11 00:27:50 backend-1   |

**Comment by return42** [comment]
Not related to SearXNG / you posted your issue into the wrong community.
