### ISSUE TITLE
Bug in `make run`

### ISSUE THREAD

**Issue by Thecode764** [searxng/searxng#3581]
Hmmmmmm idk this is a problem or no
but when i run `make run` my error is
Obtaining file:///home/.../Material-search-engine
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/null/Material-search-engine/setup.py", line 9, in <module>
          with open('README.rst', encoding='utf-8') as f:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
ERROR: ./manage: line 305: error while pip install (local/py3/bin)
make: *** [Makefile:32: install] Error 42

**Comment by Thecode764** [comment]
hmmmm i rename readme.md to readme.rst and fixed!
