### ISSUE TITLE
Geizhals cannot search for pixel 8a

### ISSUE THREAD

**Issue by cy8aer** [searxng/searxng#3685]
**SearxNG version**

SearxNG version 2024.7.27+9bbcd3713 (Container)

**How To Reproduce**

`!geiz pixel 8a`

**Expected behavior**

A list of pixel 8a is shown

**Screenshots & Logs**

This crashs with 

```
Jul 27 22:16:07 my.server.com docker[1930885]: IndexError: list index out of range
Jul 27 22:19:50 my.server.com docker[1930885]: 2024-07-27 20:19:50,713 WARNING:searx.engines.geizhals: ErrorContext('searx/engines/geizhals.py', 90, '+ extract_text(eval_xpath(result, ".//a[contains(@class, \'listview__price-link\')]")).split(" ")[1]', 'IndexError', None, ()) False
Jul 27 22:19:50 my.server.com docker[1930885]: 2024-07-27 20:19:50,713 ERROR:searx.engines.geizhals: exception : list index out of range
Jul 27 22:19:50 my.server.com docker[1930885]: Traceback (most recent call last):
Jul 27 22:19:50 my.server.com docker[1930885]:   File "/usr/local/searxng/searx/search/processors/online.py", line 163, in search
Jul 27 22:19:50 my.server.com docker[1930885]:     search_results = self._search_basic(query, params)
Jul 27 22:19:50 my.server.com docker[1930885]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 27 22:19:50 my.server.com docker[1930885]:   File "/usr/local/searxng/searx/search/processors/online.py", line 151, in _search_basic
Jul 27 22:19:50 my.server.com docker[1930885]:     return self.engine.response(response)
Jul 27 22:19:50 my.server.com docker[1930885]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 27 22:19:50 my.server.com docker[1930885]:   File "/usr/local/searxng/searx/engines/geizhals.py", line 90, in response
Jul 27 22:19:50 my.server.com docker[1930885]:     + extract_text(eval_xpath(result, ".//a[contains(@class, 'listview__price-link')]")).split(" ")[1]
Jul 27 22:19:50 my.server.com docker[1930885]:       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
Jul 27 22:19:50 my.server.com docker[1930885]: IndexError: list index out of range
```

**Additional context**

It looks like two character words with one digit makes problems: `!geiz macbook air` works, as well as `!geiz apple iphone 15`. A simple `!geiz pixel 8` works as well.

**Comment by return42** [comment]
If there are "keine Angebote" 

![image](https://github.com/user-attachments/assets/3d78d359-8d63-4492-8638-1cce41a238b4)

the expected "price" (€) is missed ..

![image](https://github.com/user-attachments/assets/da21c1da-6be8-42bf-bb9f-379f5c3db5d3)

.. I will fix it ..

**Comment by return42** [comment]
@cy8aer a patch is ready for review:

- https://github.com/searxng/searxng/pull/3688
