### ISSUE TITLE
Cannot load engine "gentoo"

### ISSUE THREAD

**Issue by xyb** [searxng/searxng#3721]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

SearXNG version 2024.8.8+dcf95644c

**How did you install SearXNG?**

git clone and docker compose up -d.

**What happened?**

No response after I input a question in web page, and the logs include:
```
2024-08-09 08:01:55,422 ERROR:searx.engines: Cannot load engine "gentoo"
Traceback (most recent call last):
  File "/usr/local/searxng/searx/engines/__init__.py", line 122, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/utils.py", line 439, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/searxng/searx/engines/gentoo.py'
2024-08-09 08:01:55,424 ERROR:searx.engines: Cannot load engine "gentoo"
Traceback (most recent call last):
  File "/usr/local/searxng/searx/engines/__init__.py", line 122, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/utils.py", line 439, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/searxng/searx/engines/gentoo.py'
2024-08-09 08:01:55,426 ERROR:searx.engines: Cannot load engine "gentoo"
Traceback (most recent call last):
  File "/usr/local/searxng/searx/engines/__init__.py", line 122, in load_engine
    engine = load_module(module_name + '.py', ENGINE_DIR)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/utils.py", line 439, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/searxng/searx/engines/gentoo.py'
2024-08-09 08:01:55,427 ERROR:searx.engines: Cannot load engine "gentoo"
```

**How To Reproduce**

Follow the guide in README.md and input a question in the web page.

**Expected behavior**

Get the anwser.

**Screenshots & Logs**

See above.

**Additional context**

None.

**Comment by return42** [comment]
Seems you have an old configuration entry in your engine settings .. the gentoo engine has been replaced by:

- https://github.com/searxng/searxng/pull/3635

The new entry is:

https://github.com/searxng/searxng/blob/f1c05e7c16e59a8d5d98640bc057958ea268cddf/searx/settings.yml#L827-L834


Problems of this kind arise if you simply copy the entire `searxng/searx/settings.yml` into your local `/etc/searxng/settings.yml`.  It is therefore recommended to use the option [`use_default_settings: true`](https://docs.searxng.org/admin/settings/settings.html#use-default-settings) in the local settings.yml and only adapt what needs to be adapted locally.

**Comment by xyb** [comment]
@return42 Sorry, found that the issue is caused by an outdated searching/settings.yml file in the Perplexica project I'm currently using. I'll submit a pull request to that project to fix this.

**Comment by return42** [comment]
@xyb FYI: I added a comment to an issue reported in the Perplexica project

- https://github.com/ItzCrazyKns/Perplexica/issues/307#issuecomment-2277508848

**Comment by AxelFooley** [comment]
Hi @return42 when you say to just put [`use_default_settings: true`] do you mean emptying the settings.yml content and just put that line at the top?

**Comment by return42** [comment]
Yes, a minimal `/etc/searxng/settings.yml` might look like:

```yaml
use_default_settings: true
server:
    secret_key: "xxxxxxxxxxxx"   # change this!
```

to enable e.g. DDG-news by default add this:

```yaml

engines:
  - name: duckduckgo news
    disabled: false
```

You have more options, just read the docs --> [use_default_settings: true](https://docs.searxng.org/admin/settings/settings.html#use-default-settings)
