### ISSUE TITLE
Support web proxy

### ISSUE THREAD

**Issue by xyb** [searxng/searxng#3723]
**Is your feature request related to a problem? Please describe.**

I work in a network environment with restrictions, and I need to configure `http_proxy`/`https_proxy` to access web services like `mediawiki`, `google`, `duckduckgo` etc. I found that even though I set the `http_proxy` environmental variables, `searxng` doesn't seem to use these proxies. Perhaps this is due to `anyio` that `searxng` is using not supporting `http_proxy`?

**Describe the solution you'd like**

Adjust `anyio`'s feature toggle for supporting `http_proxy` (assuming such a setting exists).

**Describe alternatives you've considered**

Or consider switching to an alternative package? Contribute to `anyio` to support web proxy?

**Additional context**

None.

**Comment by return42** [comment]
You can set outgoing proxies --> https://docs.searxng.org/admin/settings/settings_outgoing.html

**Comment by xyb** [comment]
There's another issue related to this one, but I'm unsure how to category it.
When starting the `searxng` service in the restricted network environment, a lot of error logs is generated, and it can be observed that there are repeated printouts of access errors for soundcloud.com up to eight times. It would be appreciated if such annoying logging could be reduced.
One sample of error logs is:
```
searxng-1              | 2024-08-09 13:47:57,757 ERROR:searx.engines.soundcloud: Fail to initialize
searxng-1              | Traceback (most recent call last):
searxng-1              |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 73, in initialize
searxng-1              |     self.engine.init(get_engine_from_settings(self.engine_name))
searxng-1              |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 69, in init
searxng-1              |     guest_client_id = get_client_id()
searxng-1              |                       ^^^^^^^^^^^^^^^
searxng-1              |   File "/usr/local/searxng/searx/engines/soundcloud.py", line 45, in get_client_id
searxng-1              |     resp = http_get("https://soundcloud.com")
searxng-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1              |   File "/usr/local/searxng/searx/network/__init__.py", line 164, in get
searxng-1              |     return request('get', url, **kwargs)
searxng-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1              |   File "/usr/local/searxng/searx/network/__init__.py", line 95, in request
searxng-1              |     return future.result(timeout)
searxng-1              |            ^^^^^^^^^^^^^^^^^^^^^^
searxng-1              |   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 456, in result
searxng-1              |     return self.__get_result()
searxng-1              |            ^^^^^^^^^^^^^^^^^^^
searxng-1              |   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
searxng-1              |     raise self._exception
searxng-1              |   File "/usr/local/searxng/searx/network/network.py", line 289, in request
searxng-1              |     return await self.call_client(False, method, url, **kwargs)
searxng-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1              |   File "/usr/local/searxng/searx/network/network.py", line 270, in call_client
searxng-1              |     response = await client.request(method, url, **kwargs)
searxng-1              |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1              |   File "/usr/lib/python3.12/site-packages/httpx/_client.py", line 1530, in request
searxng-1              |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
searxng-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1              |   File "/usr/lib/python3.12/site-packages/httpx/_client.py", line 1617, in send
searxng-1              |     response = await self._send_handling_auth(
searxng-1              |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1              |   File "/usr/lib/python3.12/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
searxng-1              |     response = await self._send_handling_redirects(
searxng-1              |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1              |   File "/usr/lib/python3.12/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
searxng-1              |     response = await self._send_single_request(request)
searxng-1              |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1              |   File "/usr/lib/python3.12/site-packages/httpx/_client.py", line 1719, in _send_single_request
searxng-1              |     response = await transport.handle_async_request(request)
searxng-1              |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1              |   File "/usr/lib/python3.12/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
searxng-1              |     resp = await self._pool.handle_async_request(req)
searxng-1              |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1              |   File "/usr/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 262, in handle_async_request
searxng-1              |     raise exc
searxng-1              |   File "/usr/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
searxng-1              |     response = await connection.handle_async_request(request)
searxng-1              |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1              |   File "/usr/lib/python3.12/site-packages/httpcore/_async/connection.py", line 92, in handle_async_request
searxng-1              |     raise exc
searxng-1              |   File "/usr/lib/python3.12/site-packages/httpcore/_async/connection.py", line 69, in handle_async_request
searxng-1              |     stream = await self._connect(request)
searxng-1              |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1              |   File "/usr/lib/python3.12/site-packages/httpcore/_async/connection.py", line 149, in _connect
searxng-1              |     stream = await stream.start_tls(**kwargs)
searxng-1              |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1              |   File "/usr/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 78, in start_tls
searxng-1              |     raise exc
searxng-1              |   File "/usr/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 69, in start_tls
searxng-1              |     ssl_stream = await anyio.streams.tls.TLSStream.wrap(
searxng-1              |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng-1              |   File "/usr/lib/python3.12/site-packages/anyio/streams/tls.py", line 132, in wrap
searxng-1              |     await wrapper._call_sslobject_method(ssl_object.do_handshake)
searxng-1              |   File "/usr/lib/python3.12/site-packages/anyio/streams/tls.py", line 140, in _call_sslobject_method
searxng-1              |     result = func(*args)
searxng-1              |              ^^^^^^^^^^^
searxng-1              |   File "/usr/lib/python3.12/ssl.py", line 917, in do_handshake
searxng-1              |     self._sslobj.do_handshake()
searxng-1              | ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'soundcloud.com'. (_ssl.c:1000)
```

**Comment by return42** [comment]
Its caused by the initialization of the soundcloud engine .. if you have more than one process or workers it will initialize n-times resulting in n-error messages :-(

> It would be appreciated if such annoying logging could be reduced.

If you have SSL CERT errors only with soundcloud and you don't need soundcloud, you get rid of this engine by set it inactive in your settings:

```yaml
  - name: soundcloud
    inactive: true
```

**Comment by xyb** [comment]
> You can set outgoing proxies --> https://docs.searxng.org/admin/settings/settings_outgoing.html

Cool, that works for me.

> Its caused by the initialization of the soundcloud engine .. if you have more than one process or workers it will initialize n-times resulting in n-error messages :-(

Oh, of course, that make sense, my computer have 8 cpu cores:
```
searxng-1              | detected number of CPU cores: 8
```

And I notice that my proxy's log shows, on the initialize stage, few sites like `wikidata`/`duckduckgo` be visited 8 times also. But, that's not a big deal as long as there are not many error messages.

**Comment by return42** [comment]
> Oh, of course, that make sense, my computer have 8 cpu cores:

IDK the architecture of Perplexica, but may you prefer to reduce the workers (will also reduce the memory footprint):

https://github.com/ItzCrazyKns/Perplexica/blob/9c1936ec2cb0a18389c6037895c30aab416243b9/searxng/uwsgi.ini#L6-L8

**Comment by xyb** [comment]
> > Oh, of course, that make sense, my computer have 8 cpu cores:
> 
> IDK the architecture of Perplexica, but may you prefer to reduce the workers (will also reduce the memory footprint):
> 
> https://github.com/ItzCrazyKns/Perplexica/blob/9c1936ec2cb0a18389c6037895c30aab416243b9/searxng/uwsgi.ini#L6-L8

Thanks @return42, that's very helpful.

**Comment by gerroon** [comment]
> You can set outgoing proxies --> https://docs.searxng.org/admin/settings/settings_outgoing.html

Hi Thanks for the reply. Is it correct to say that SearxNG only supports SOCKS proxy? I need to use http_proxy in Docker.

**Comment by xyb** [comment]
> > You can set outgoing proxies --> https://docs.searxng.org/admin/settings/settings_outgoing.html
> 
> Hi Thanks for the reply. Is it correct to say that SearxNG only supports SOCKS proxy? I need to use http_proxy in Docker.

@gerroon You can set proxies that httpx supports, including http proxy, in outgoing section of SearxNG's configuration. Here's mine for example:
```yaml
use_default_settings: true

general:
  instance_name: 'searxng'
  debug: true

search:
  autocomplete: 'google'
  formats:
    - html
    - json

outgoing:
  proxies:
    all://:
      - http://192.168.1.150:7890

server:
  secret_key: 'mysecretkey' # Is overwritten by ${SEARXNG_SECRET}

engines:
  - name: wolframalpha
    disabled: false

  - name: soundcloud
    inactive: true
```
