### ISSUE TITLE
Bug: tineye engine

### ISSUE THREAD

**Issue by return42** [searxng/searxng#3728]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.8.9

**How did you install SearXNG?**

`make run`

**How To Reproduce**

reverse search for an image `!tin https://hekint.org/wp-content/uploads/2019/11/1989.1_Fountain-of-Milk_web-768x667.jpg`

**What happened?**

Seems the response from tineye has changed in the past and we need to adapt the new response:

```
Traceback (most recent call last):
  File "searx/search/processors/online.py", line 163, in search
    search_results = self._search_basic(query, params)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "searx/search/processors/online.py", line 151, in _search_basic
    return self.engine.response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "searx/engines/tineye.py", line 196, in response
    for match_json in json_data['matches']:
                      ~~~~~~~~~^^^^^^^^^^^
KeyError: 'matches'
```
**Technical report**

Error
  * Error: KeyError
  * Percentage: 100
  * Parameters: `()`
  * File name: `searx/engines/tineye.py:196`
  * Function: `response`
  * Code: `for match_json in json_data['matches']:`

**Comment by glanham-jr** [comment]
Going to dump my investigation results below:

Post URL: https://tineye.com/api/v1/result_json/?sort=score&order=desc

I just tried to use TinEye directly for that image, and received an error.

![image](https://github.com/user-attachments/assets/a6640607-7e95-47c6-903a-4c14ae98dd61)

What is strange that after a few tries, it seems to be working now and I cannot reproduce the error. Regardless, to replicate an error, I just entered an invalid URL (I just chopped off the extension in the image you provided).

The error JSON doesn't have a `matches` result, but is formatted as follows:

```json
{
  "page": 1,
  "sort_selector": null,
  "limit": 10,
  "domain_name": "",
  "no_cache": false,
  "image_server": "https://img.tineye.com/",
  "load_query_summary": false,
  "show_unavailable_domains": false,
  "sort": "score",
  "order": "desc",
  "domain": "",
  "tags": "",
  "offset": 0,
  "suggestions": {
    "key": "Download Error",
    "title": "Oops, something didn't work!",
    "suggestions": [],
    "description": [
      "TinEye could not read that image url. This may be due to an unsupported file format. TinEye only supports images that are JPEG, PNG, GIF, BMP, TIFF or WebP. Try downloading your image from the website, and <a onclick=\"javascript:document.getElementById('upload_box').click()\">uploading it directly</a> to TinEye."
    ]
  },
  "http_code": 422
}
```

The `http_code` is the same as the header status code: 422.

Below is the successful response, matches removed for brevity.

```json
{
  "page": 1,
  "sort_selector": null,
  "limit": 10,
  "domain_name": "",
  "no_cache": false,
  "image_server": "https://img.tineye.com/",
  "load_query_summary": false,
  "show_unavailable_domains": false,
  "sort": "score",
  "order": "desc",
  "domain": "",
  "tags": "",
  "offset": 0,
  "query_hash": "8c300218c491976c5fdeb646592252fcab656cca",
  "start": 0,
  "end": 10,
  "total_pages": 4,
  "query": {
    "key": "8c300218c491976c5fdeb646592252fcab656cca",
    "width": 768,
    "height": 667,
    "filesize": 108811,
    "hash": "033b27f4f6978c14e963d1471da034c85c53ec27"
  },
  "matches": [
    {
      "image_url": "https://img.tineye.com/result/4bf8017c521daae9dae4c2ee6bddfcba7e8e56598f18da954eeebf1914449dca-3",
      "key": "4bf8017c521daae9dae4c2ee6bddfcba7e8e56598f18da954eeebf1914449dca",
      "transform": {
        "m11": 0.4382309913635254,
        "m12": 0.003875369904562831,
        "m13": -5.0378098487854,
        "m21": -0.003875369904562831,
        "m22": 0.4382309913635254,
        "m23": -2.5049901008605957
      },
      "domain": "salvador-dali.org",
      "domain_unavailable": false,
      "score": 61.4379997253418,
      "width": 800,
      "height": 694,
      "size": 555200,
      "format": "JPEG",
      "filesize": 273587,
      "overlay": "overlay/033b27f4f6978c14e963d1471da034c85c53ec27/4bf8017c521daae9dae4c2ee6bddfcba7e8e56598f18da954eeebf1914449dca?m11=0.4382309913635254&m12=0.003875369904562831&m13=-5.0378098487854&m21=-0.003875369904562831&m22=0.4382309913635254&m23=-2.5049901008605957",
      "matching_features": 94,
      "backlinks": [
        {
          "url": "http://www.salvador-dali.org/cataleg_raonat/imatge.php?amplia&imatge=CATIMA02.jpg",
          "backlink": "http://www.salvador-dali.org/cataleg_raonat/resized_imatge.php?imatge=1&obra=602",
          "crawl_date": "2013-08-10",
          "source_id": null,
          "image_name": "imatge.php"
        }
      ],
      "tags": [],
      "promoted": false,
      "domains": [
        {
          "domain_name": "www.salvador-dali.org",
          "image_name": "imatge.php",
          "backlinks": [
            {
              "url": "http://www.salvador-dali.org/cataleg_raonat/imatge.php?amplia&imatge=CATIMA02.jpg",
              "backlink": "http://www.salvador-dali.org/cataleg_raonat/resized_imatge.php?imatge=1&obra=602",
              "crawl_date": "2013-08-10",
              "source_id": null,
              "image_name": "imatge.php"
            }
          ]
        }
      ]
    }
  ],
  "num_matches": 38,
  "num_filtered_matches": 36,
  "num_collection_matches": 0,
  "num_stock_matches": 0,
  "num_unavailable_matches": 2,
  "str_num_matches": "38 results",
  "str_search_time": "0.5 seconds",
  "query_source": "https://hekint.org/wp-content/uploads/2019/11/1989.1_Fountain-of-Milk_web-768x667.jpg"
}

```


**Suggestion**

Looks like the code should handle this, will need to investigate why the correct error code path is not begin hit.

**Comment by glanham-jr** [comment]
Ran it locally and dumped the result. The JSON itself is wrong, and for some reason the TinEye engine swallows the error.

![image](https://github.com/user-attachments/assets/a60f0c1c-0b31-4eed-b1c7-e3903ac47bd1)

**Comment by return42** [comment]
closed by: https://github.com/searxng/searxng/pull/3746
