### ISSUE TITLE
Instant answering modules return HTTP code 500

### ISSUE THREAD

**Issue by shreven0** [searxng/searxng#3820]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

2024.9.12+9e2bfe14d

**How did you install SearXNG?**

Manually on OpenBSD (really cool OS btw)

**What happened?**

The server returned HTTP 500

**How To Reproduce**

[Search for random something](https://searxng.shreven.org/search?q=random+uuid) or any of the statistical functions (min, max, avg, sum, prod) and the error should occur.

**Expected behavior**

A 200 response code with a page displaying the results of my query

**Comment by monofox** [comment]
Example stacktrace in case of `random uuid`:
```
2024-09-13 15:39:18,214 ERROR:searx.webapp: Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/webapp.py", line 772, in search
    return render(
           ^^^^^^^
  File "/usr/local/searxng/searx/webapp.py", line 464, in render
    result = render_template('{}/{}'.format(kwargs['theme'], template_name), **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/searxng/searx/templates/simple/results.html", line 6, in top-level template code
    <input type="hidden" name="engine_data-{{ engine_name }}-{{ k|e }}" value="{{ v|e }}" />
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/templates/simple/base.html", line 63, in top-level template code
    {% block content %}
  File "/usr/local/searxng/searx/templates/simple/results.html", line 60, in block 'content'
    {%- include 'simple/elements/engines_msg.html' -%}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/templates/simple/elements/engines_msg.html", line 7, in top-level template code
    <summary class="title" id="engines_msg-title">{{ _('Response time') }}: {{ max_response_time | round(1) }} {{ _('seconds') }}</summary>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/jinja2/filters.py", line 1169, in do_round
    return round(value, precision)
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: type NoneType doesn't define __round__ method
```

Probably `max_response_time` is None. Introduced with #3755
