### ISSUE TITLE
Calculator Plugin Errors When Using Decimal Values In Search Bar

### ISSUE THREAD

**Issue by fostro** [searxng/searxng#3854]
Container Image:  docker.io/searxng/searxng:latest

When the calculator plugin is enabled, trying to pass in any equation that contains decimal values (floating point math) throws the following error

```
searxng        | 2024-09-24T20:20:16.381773929Z Process Process-6:                                                                                                                                                                           
searxng        | 2024-09-24T20:20:16.383401418Z Traceback (most recent call last):                                                                                                                                                           
searxng        | 2024-09-24T20:20:16.384448893Z   File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap                                                                                                             
searxng        | 2024-09-24T20:20:16.384466676Z     self.run()                                                                                                                                                                               
searxng        | 2024-09-24T20:20:16.384507243Z   File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run                                                                                                                    
searxng        | 2024-09-24T20:20:16.384518744Z     self._target(*self._args, **self._kwargs)                                                                                                                                                
searxng        | 2024-09-24T20:20:16.384640545Z   File "/usr/local/searxng/searx/plugins/calculator.py", line 62, in handler                                                                                                                 
searxng        | 2024-09-24T20:20:16.384652938Z     q.put(func(*args, **kwargs))                                                                                                                                                             
searxng        | 2024-09-24T20:20:16.384658509Z           ^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                              
searxng        | 2024-09-24T20:20:16.385008178Z   File "/usr/local/searxng/searx/plugins/calculator.py", line 42, in _eval_expr                                                                                                              
searxng        | 2024-09-24T20:20:16.385034477Z     return _eval(ast.parse(expr, mode='eval').body)                                                                                                                                          
searxng        | 2024-09-24T20:20:16.385041711Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                          
searxng        | 2024-09-24T20:20:16.385439661Z   File "/usr/local/searxng/searx/plugins/calculator.py", line 50, in _eval                                                                                                                   
searxng        | 2024-09-24T20:20:16.385458727Z     return operators[type(node.op)](_eval(node.left), _eval(node.right))                                                                                                                     
searxng        | 2024-09-24T20:20:16.385467012Z                                     ^^^^^^^^^^^^^^^^                                                                                                                                         
searxng        | 2024-09-24T20:20:16.385613599Z   File "/usr/local/searxng/searx/plugins/calculator.py", line 55, in _eval                                                                                                                   
searxng        | 2024-09-24T20:20:16.385627936Z     raise TypeError(node)                                                                                                                                                                    
searxng        | 2024-09-24T20:20:16.385638225Z TypeError: <ast.Constant object at 0x7f91ce77ff10>
```

**Comment by Bnyro** [comment]
This should be opened at the main repository, not the Docker repo.

**Comment by fostro** [comment]
Is there any update on how to fix this issue?  This makes the calculator plugin significantly less useful if it only works with integers.

**Comment by return42** [comment]
Sorry for the delay ..  I had an additional exception (see below). I think the expression (the numbers) need to be localized and parsed (see babel's [number parsing](https://babel.pocoo.org/en/latest/api/numbers.html#number-parsing)) / Here are two examples that should both lead to the same result:

- `:en 1.01 + 7.02`
- `:de 1.01 + 7.02`


------

```
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/share/searxng/searx/plugins/calculator.py", line 62, in handler
    q.put(func(*args, **kwargs))
          ^^^^^^^^^^^^^^^^^^^^^
  File "/share/searxng/searx/plugins/calculator.py", line 42, in _eval_expr
    return _eval(ast.parse(expr, mode='eval').body)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/ast.py", line 52, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 1
    1,01 + 7,02
      ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
```

**Comment by return42** [comment]
closed by https://github.com/searxng/searxng/pull/3885
