### ISSUE TITLE
MariaDB Support

### ISSUE THREAD

**Issue by unclemusclez** [searxng/searxng#3859]
I am trying to access a mariadb sql database, however, the python engine seems to be buggy with mariadb. is support for mariadb something that would be considered?

```
2024-09-28 13:37:57,969 ERROR:searx.engines.rss: Fail to initialize
Traceback (most recent call last):
  File "/usr/local/searxng/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Unknown collation: 'utf8mb4_0900_ai_ci'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/searxng/src/searx/search/processors/abstract.py", line 73, in initialize
    self.engine.init(get_engine_from_settings(self.engine_name))
  File "/usr/local/searxng/src/searx/engines/mysql_server.py", line 58, in init
    _connection = mysql.connector.connect(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/.venv/lib/python3.12/site-packages/mysql/connector/pooling.py", line 322, in connect
    return CMySQLConnection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 151, in __init__
    self.connect(**kwargs)
  File "/usr/local/searxng/.venv/lib/python3.12/site-packages/mysql/connector/abstracts.py", line 1411, in connect
    self._post_connection()
  File "/usr/local/searxng/.venv/lib/python3.12/site-packages/mysql/connector/abstracts.py", line 1351, in _post_connection
    self.set_charset_collation(charset=self._charset_id)
  File "/usr/local/searxng/.venv/lib/python3.12/site-packages/mysql/connector/abstracts.py", line 1326, in set_charset_collation
    self._execute_query(f"SET NAMES '{charset_name}' COLLATE '{collation_name}'")
  File "/usr/local/searxng/.venv/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 713, in cmd_query
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 1273 (HY000): Unknown collation: 'utf8mb4_0900_ai_ci'
2024-09-28 13:37:57,970 ERROR:searx.engines.rss: Fail to initialize
Traceback (most recent call last):
  File "/usr/local/searxng/.venv/lib/python3.12/site-packages/mysql/connector/connection_cext.py", line 705, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Unknown collation: 'utf8mb4_0900_ai_ci'

```
```
Traceback (most recent call last):
  File "/usr/local/searxng/src/searx/search/processors/offline.py", line 19, in search
    search_results = self._search_basic(query, params)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/src/searx/search/processors/offline.py", line 15, in _search_basic
    return self.engine.search(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/src/searx/engines/mysql_server.py", line 72, in search
    with _connection.cursor() as cur:
         ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cursor'
```

**Comment by return42** [comment]
You can not connect to a MariaDB with the [MySQL](https://docs.searxng.org/dev/engines/offline/sql-engines.html#engine-mysql-server) connector, a [MariaDB](https://pypi.org/project/mariadb/) connector is needed .. TBH this needs to implement a new engine for MariaDB --> I tagged you issue to be an `engine request` (and removed the `bug` tag) .. PRs are welcome :smile:

**Comment by unclemusclez** [comment]
i dont think i'm smart smart enough for this, but i was looking at making a pr for the huggingface api repo search. 

i figured this would require a separate engine because of the python backend. thanks for the help. i look forward to any development

**Comment by glanham-jr** [comment]
@unclemusclez I have a PR open for this development. Would you be able to pull my branch down and test it for your setup?

**Comment by unclemusclez** [comment]
@glanham-jr 🕯️🙏🕯️

i gotta redo a few things i will get back to you very soon i appreciate it.

**Comment by glanham-jr** [comment]
@return42 I saw you cleanup some issues, we can probably complete this one as well.
