### ISSUE TITLE
Bug: duckduckgo engine (and other engines)

### ISSUE THREAD

**Issue by pluim003** [searxng/searxng#3890]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.10.4+3e747d049

**How did you install SearXNG?**

Through Docker with the container searxng/searxng

**What happened?**

Every search results in timeouts. To be honest I haven't used searxng in a while and I moved my Raspberry Pi4 from one network to another network. But when I do a search I see that my pihole is receiving these requests and succeeds. Also disabling pihole doesn't solve it. And there are a lot of python-errors thrown.

**How To Reproduce**

Good question. Try running it in a docker container on a RPi4.

**Expected behavior**
I expect search results like the other public search sites show.

**Screenshots & Logs**
Logfile:

2024-10-05T14:21:18.247888449Z   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
2024-10-05T14:21:18.247893690Z     self.gen.throw(value)
2024-10-05T14:21:18.247898579Z   File "/usr/lib/python3.12/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
2024-10-05T14:21:18.247904098Z     raise mapped_exc(message) from exc
2024-10-05T14:21:18.247909005Z httpx.ConnectError: [Errno -3] Try again
2024-10-05T14:21:18.247914061Z 2024-10-05 14:21:18,241 WARNING:searx.engines.duckduckgo: ErrorContext('searx/engines/duckduckgo.py', 119, 'res = get(query_url)', 'httpx.ConnectError', None, (None, None, 'duckduckgo.com')) False
2024-10-05T14:21:18.254010620Z 2024-10-05 14:21:18,247 ERROR:searx.engines.duckduckgo: requests exception (search duration : 5.1468625249981415 s, timeout: 10.0 s) : [Errno -3] Try again
2024-10-05T14:21:18.254074471Z Traceback (most recent call last):
2024-10-05T14:21:18.254082305Z   File "/usr/lib/python3.12/site-packages/anyio/_core/_sockets.py", line 187, in connect_tcp
2024-10-05T14:21:18.254088971Z     addr_obj = ip_address(remote_host)
2024-10-05T14:21:18.254094823Z                ^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05T14:21:18.254100231Z   File "/usr/lib/python3.12/ipaddress.py", line 54, in ip_address
2024-10-05T14:21:18.254105749Z     raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
2024-10-05T14:21:18.254111434Z ValueError: 'duckduckgo.com' does not appear to be an IPv4 or IPv6 address
2024-10-05T14:21:18.254116934Z 
2024-10-05T14:21:18.254121860Z During handling of the above exception, another exception occurred:
2024-10-05T14:21:18.254127230Z 
2024-10-05T14:21:18.254132119Z Traceback (most recent call last):
2024-10-05T14:21:18.254137138Z   File "/usr/lib/python3.12/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
2024-10-05T14:21:18.254142823Z     yield
2024-10-05T14:21:18.254147823Z   File "/usr/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
2024-10-05T14:21:18.254153342Z     stream: anyio.abc.ByteStream = await anyio.connect_tcp(
2024-10-05T14:21:18.254158619Z                                    ^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05T14:21:18.254163842Z   File "/usr/lib/python3.12/site-packages/anyio/_core/_sockets.py", line 190, in connect_tcp
2024-10-05T14:21:18.254169379Z     gai_res = await getaddrinfo(
2024-10-05T14:21:18.254174379Z               ^^^^^^^^^^^^^^^^^^
2024-10-05T14:21:18.254179304Z   File "/usr/lib/python3.12/site-packages/anyio/_core/_sockets.py", line 568, in getaddrinfo
2024-10-05T14:21:18.254184730Z     gai_res = await get_async_backend().getaddrinfo(
2024-10-05T14:21:18.254212341Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05T14:21:18.254219378Z   File "/usr/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2403, in getaddrinfo
2024-10-05T14:21:18.254225027Z     return await get_running_loop().getaddrinfo(
2024-10-05T14:21:18.254230138Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05T14:21:18.254235138Z   File "uvloop/loop.pyx", line 1528, in getaddrinfo
2024-10-05T14:21:18.254240286Z socket.gaierror: [Errno -3] Try again
2024-10-05T14:21:18.254245175Z 
2024-10-05T14:21:18.254249897Z The above exception was the direct cause of the following exception:
2024-10-05T14:21:18.254255082Z 
2024-10-05T14:21:18.254259860Z Traceback (most recent call last):
2024-10-05T14:21:18.254264804Z   File "/usr/lib/python3.12/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
2024-10-05T14:21:18.254270304Z     yield
2024-10-05T14:21:18.254275119Z   File "/usr/lib/python3.12/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
2024-10-05T14:21:18.254280656Z     resp = await self._pool.handle_async_request(req)
2024-10-05T14:21:18.254288230Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05T14:21:18.254294193Z   File "/usr/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 262, in handle_async_request
2024-10-05T14:21:18.254299971Z     raise exc
2024-10-05T14:21:18.254304878Z   File "/usr/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
2024-10-05T14:21:18.254310415Z     response = await connection.handle_async_request(request)
2024-10-05T14:21:18.254315712Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05T14:21:18.254320934Z   File "/usr/lib/python3.12/site-packages/httpcore/_async/connection.py", line 92, in handle_async_request
2024-10-05T14:21:18.254326434Z     raise exc
2024-10-05T14:21:18.254331415Z   File "/usr/lib/python3.12/site-packages/httpcore/_async/connection.py", line 69, in handle_async_request
2024-10-05T14:21:18.254336952Z     stream = await self._connect(request)
2024-10-05T14:21:18.254342026Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05T14:21:18.254347119Z   File "/usr/lib/python3.12/site-packages/httpcore/_async/connection.py", line 117, in _connect
2024-10-05T14:21:18.254352582Z     stream = await self._network_backend.connect_tcp(**kwargs)
2024-10-05T14:21:18.254357804Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05T14:21:18.254363008Z   File "/usr/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 31, in connect_tcp
2024-10-05T14:21:18.254368508Z     return await self._backend.connect_tcp(
2024-10-05T14:21:18.254373526Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05T14:21:18.254378656Z   File "/usr/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 112, in connect_tcp
2024-10-05T14:21:18.254391971Z     with map_exceptions(exc_map):
2024-10-05T14:21:18.254398619Z          ^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05T14:21:18.254403748Z   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
2024-10-05T14:21:18.254409230Z     self.gen.throw(value)
2024-10-05T14:21:18.254414230Z   File "/usr/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2024-10-05T14:21:18.254419785Z     raise to_exc(exc) from exc
2024-10-05T14:21:18.254424767Z httpcore.ConnectError: [Errno -3] Try again
2024-10-05T14:21:18.254429804Z 
2024-10-05T14:21:18.254434600Z The above exception was the direct cause of the following exception:
2024-10-05T14:21:18.254440063Z 
2024-10-05T14:21:18.254444933Z Traceback (most recent call last):
2024-10-05T14:21:18.254450007Z   File "/usr/local/searxng/searx/search/processors/online.py", line 163, in search
2024-10-05T14:21:18.254455507Z     search_results = self._search_basic(query, params)
2024-10-05T14:21:18.254460693Z                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05T14:21:18.254465878Z   File "/usr/local/searxng/searx/search/processors/online.py", line 137, in _search_basic
2024-10-05T14:21:18.254471322Z     self.engine.request(query, params)
2024-10-05T14:21:18.254784136Z   File "/usr/local/searxng/searx/engines/duckduckgo.py", line 244, in request
2024-10-05T14:21:18.254807321Z     vqd = get_vqd(query)
2024-10-05T14:21:18.254813136Z           ^^^^^^^^^^^^^^
2024-10-05T14:21:18.254818247Z   File "/usr/local/searxng/searx/engines/duckduckgo.py", line 119, in get_vqd
2024-10-05T14:21:18.254823599Z     res = get(query_url)
2024-10-05T14:21:18.254828395Z           ^^^^^^^^^^^^^^
2024-10-05T14:21:18.254833247Z   File "/usr/local/searxng/searx/network/__init__.py", line 164, in get
2024-10-05T14:21:18.254838581Z     return request('get', url, **kwargs)
2024-10-05T14:21:18.254843544Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05T14:21:18.254848858Z   File "/usr/local/searxng/searx/network/__init__.py", line 95, in request
2024-10-05T14:21:18.254854136Z     return future.result(timeout)
2024-10-05T14:21:18.254859099Z            ^^^^^^^^^^^^^^^^^^^^^^
2024-10-05T14:21:18.254864044Z   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 456, in result
2024-10-05T14:21:18.254869321Z     return self.__get_result()
2024-10-05T14:21:18.254874173Z            ^^^^^^^^^^^^^^^^^^^
2024-10-05T14:21:18.254879025Z   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
2024-10-05T14:21:18.254884340Z     raise self._exception
2024-10-05T14:21:18.254889229Z   File "/usr/local/searxng/searx/network/network.py", line 289, in request
2024-10-05T14:21:18.254908284Z     return await self.call_client(False, method, url, **kwargs)
2024-10-05T14:21:18.254915136Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05T14:21:18.254920358Z   File "/usr/local/searxng/searx/network/network.py", line 285, in call_client
2024-10-05T14:21:18.254925691Z     raise e
2024-10-05T14:21:18.254930488Z   File "/usr/local/searxng/searx/network/network.py", line 270, in call_client
2024-10-05T14:21:18.254935766Z     response = await client.request(method, url, **kwargs)
2024-10-05T14:21:18.254940858Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-05T14:21:18.254945988Z   File "/usr/lib/python3.12/site-packages/httpx/_client.py", line 1530, in request
2024-10-05T14:21:18.254951340Z     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
2024-10-05T14:21:18.254956599Z            

**Additional context**
See above.

**Technical report**

**Comment by pluim003** [comment]
Hmmm... found this issue: https://github.com/searx/searx/issues/3405 and used that solution and created a docker-compose.yaml-file and added another dns and that solved the problem and also no python-errors.

**Comment by return42** [comment]
- duplicate: https://github.com/searxng/searxng/issues/3626#issuecomment-2198149381

**Comment by quentinsf** [comment]
Just FYI, I've started getting this now -- the GUI is working but all connections to search engines are timing out -- and neither adding a dns clause to the compose file nor disabling HTTP2 (both solutions I've seen elsewhere) -- seem to solve it.
This is just in case others are still seeing it too.
