### ISSUE TITLE
Issue with missing tomli module after upgrade

### ISSUE THREAD

**Issue by LyndonArmitage** [searxng/searxng#3896]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

Git hash: 5332d3a0b8f94a7a984d22cbcfa1fb9c34cb3ff9

**How did you install SearXNG?**

I had originally installed searx a long time ago and then migrated to searxng. I believe I followed the wiki steps to migrate, and used `sudo -H ./utils/searxng.sh install all`

**What happened?**

I was manually upgrading my searxng install, and encountered a failure in deployment after executing the standard upgrade script. This left nginx giving me a 500 error response code.

I was able to workaround this by manually installing a missing python dependency (tomli) into the virtual environment searxng uses. I'll leave detailed steps at the end of this report for anyone with a similar issue.

**How To Reproduce**

Run `sudo -H ./utils/searxng.sh instance update` in `/usr/local/searxng/searxng-src` from a version previous to the current one mentioned.

Unfortunately I didn't keep track of the previous version I was on before this update.

**Expected behavior**

Git changes should be pulled and Python dependencies updated successfully (including installing any new dependencies) 

**Screenshots & Logs**

This is a snippet of my log file from when it broke:

```
Mon Oct  7 10:14:34 2024 - --- no python application found, check your startup logs for errors ---
Traceback (most recent call last):
  File "/usr/local/searxng/searxng-src/searx/webapp.py", line 1355, in <module>
    favicons.init()
  File "/usr/local/searxng/searxng-src/searx/favicons/__init__.py", line 24, in init
    from . import config, cache, proxy
  File "/usr/local/searxng/searxng-src/searx/favicons/config.py", line 9, in <module>
    from searx.compat import tomllib
  File "/usr/local/searxng/searxng-src/searx/compat.py", line 18, in <module>
    import tomli as tomllib
ModuleNotFoundError: No module named 'tomli'
Mon Oct  7 10:14:34 2024 - unable to load app 0 (mountpoint='') (callable not found or import error)
```

**Additional context**

I was able to work around this issue by manually installing the tomli dependency into the searxng python environment by doing the following:

```sh
sudo su - searxng
cd /usr/local/searxng/
source searx-pyenv/bin/activate
pip install tomli
```

This can probably be low priority if nobody else has experienced similar, but I thought it prudent to report the issue in case others run into it.

**Comment by return42** [comment]
Thanks for your report :+1: / some additions ..

`sudo -H ./utils/searxng.sh instance update` calls function `searxng.instance.update()`: 

https://github.com/searxng/searxng/blob/5332d3a0b8f94a7a984d22cbcfa1fb9c34cb3ff9/utils/searxng.sh#L568-L591

May git calls fail:

```
 git fetch origin "$GIT_BRANCH" 
 git reset --hard "origin/$GIT_BRANCH" 
```

or the pip install fail for some unknown reason?

```
pip install -U --use-pep517 --no-build-isolation -e .
````

**Comment by LyndonArmitage** [comment]
Thanks for pointing that out. To add to this, the update process "succeeded". That is to say, it didn't seemingly report any obvious failures (the error code remained 0). I don't have the logs for the responses to this as I had closed my terminal assuming a success.

**Comment by markmixx** [comment]
I ran into this issue updating from 2024.7.20+657dcb973 to 2024.10.11+1b8db63b3 and the above workaround was successful (thanks!).

The instance update appeared to complete without any visible errors but there was an error in the output during the `pip install -U -e .` 

Full log:

```
$ sudo -H ./utils/searxng.sh instance update 

Update SearXNG instance
=======================

fetch from https://github.com/searxng/searxng and reset to origin/master
cd /usr/local/searxng/searxng-src
git fetch origin "master"
git reset --hard "origin/master"
pip install -U pip
pip install -U setuptools
  |searxng| From https://github.com/searxng/searxng
  |searxng|  * branch                master     -> FETCH_HEAD
  |searxng|    657dcb973..1b8db63b3  master     -> origin/master
pip install -U wheel
  |searxng| HEAD is now at 1b8db63b3 [upd] pypi: Bump pydantic from 2.8.2 to 2.9.2
pip install -U pyyaml
  |searxng| Requirement already satisfied: pip in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (24.1.2)
  |searxng| Collecting pip
  |searxng|   Downloading pip-24.2-py3-none-any.whl.metadata (3.6 kB)
  |searxng| Downloading pip-24.2-py3-none-any.whl (1.8 MB)
  |searxng|    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 40.3 MB/s eta 0:00:00
pip install -U -e .
  |searxng| Installing collected packages: pip
  |searxng|   Attempting uninstall: pip
  |searxng|     Found existing installation: pip 24.1.2
  |searxng|     Uninstalling pip-24.1.2:
  |searxng|       Successfully uninstalled pip-24.1.2
  |searxng| Successfully installed pip-24.2
  |searxng| Requirement already satisfied: setuptools in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (71.1.0)
  |searxng| Collecting setuptools
  |searxng|   Downloading setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
  |searxng| Downloading setuptools-75.1.0-py3-none-any.whl (1.2 MB)
  |searxng|    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 65.4 MB/s eta 0:00:00
  |searxng| Installing collected packages: setuptools
  |searxng|   Attempting uninstall: setuptools
  |searxng|     Found existing installation: setuptools 71.1.0
  |searxng|     Uninstalling setuptools-71.1.0:
  |searxng|       Successfully uninstalled setuptools-71.1.0
  |searxng| Successfully installed setuptools-75.1.0
  |searxng| Requirement already satisfied: wheel in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (0.43.0)
  |searxng| Collecting wheel
  |searxng|   Downloading wheel-0.44.0-py3-none-any.whl.metadata (2.3 kB)
  |searxng| Downloading wheel-0.44.0-py3-none-any.whl (67 kB)
  |searxng| Installing collected packages: wheel
  |searxng|   Attempting uninstall: wheel
  |searxng|     Found existing installation: wheel 0.43.0
  |searxng|     Uninstalling wheel-0.43.0:
  |searxng|       Successfully uninstalled wheel-0.43.0
  |searxng| Successfully installed wheel-0.44.0
  |searxng| Requirement already satisfied: pyyaml in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (6.0.1)
  |searxng| Collecting pyyaml
  |searxng|   Downloading PyYAML-6.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
  |searxng| Downloading PyYAML-6.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (737 kB)
  |searxng|    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 737.4/737.4 kB 50.6 MB/s eta 0:00:00
  |searxng| Installing collected packages: pyyaml
  |searxng|   Attempting uninstall: pyyaml
  |searxng|     Found existing installation: PyYAML 6.0.1
  |searxng|     Uninstalling PyYAML-6.0.1:
  |searxng|       Successfully uninstalled PyYAML-6.0.1
  |searxng| ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
  |searxng| searxng 2024.7.20+657dcb973 requires pyyaml==6.0.1, but you have pyyaml 6.0.2 which is incompatible.
  |searxng| Successfully installed pyyaml-6.0.2
  |searxng| Obtaining file:///usr/local/searxng/searxng-src
  |searxng|   Preparing metadata (setup.py): started
  |searxng|   Preparing metadata (setup.py): finished with status 'done'
  |searxng| Collecting certifi==2024.8.30 (from searxng==2024.10.11+1b8db63b3)
  |searxng|   Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
  |searxng| Collecting babel==2.16.0 (from searxng==2024.10.11+1b8db63b3)
  |searxng|   Downloading babel-2.16.0-py3-none-any.whl.metadata (1.5 kB)
  |searxng| Requirement already satisfied: flask-babel==4.0.0 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from searxng==2024.10.11+1b8db63b3) (4.0.0)
  |searxng| Requirement already satisfied: flask==3.0.3 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from searxng==2024.10.11+1b8db63b3) (3.0.3)
  |searxng| Requirement already satisfied: jinja2==3.1.4 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from searxng==2024.10.11+1b8db63b3) (3.1.4)
  |searxng| Collecting lxml==5.3.0 (from searxng==2024.10.11+1b8db63b3)
  |searxng|   Downloading lxml-5.3.0-cp39-cp39-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
  |searxng| Requirement already satisfied: pygments==2.18.0 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from searxng==2024.10.11+1b8db63b3) (2.18.0)
  |searxng| Requirement already satisfied: python-dateutil==2.9.0.post0 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from searxng==2024.10.11+1b8db63b3) (2.9.0.post0)
  |searxng| Requirement already satisfied: pyyaml==6.0.2 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from searxng==2024.10.11+1b8db63b3) (6.0.2)
  |searxng| Requirement already satisfied: httpx==0.24.1 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from httpx[http2]==0.24.1->searxng==2024.10.11+1b8db63b3) (0.24.1)
  |searxng| Requirement already satisfied: Brotli==1.1.0 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from searxng==2024.10.11+1b8db63b3) (1.1.0)
  |searxng| Collecting uvloop==0.20.0 (from searxng==2024.10.11+1b8db63b3)
  |searxng|   Downloading uvloop-0.20.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
  |searxng| Requirement already satisfied: httpx-socks==0.7.7 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from httpx-socks[asyncio]==0.7.7->searxng==2024.10.11+1b8db63b3) (0.7.7)
  |searxng| Requirement already satisfied: setproctitle==1.3.3 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from searxng==2024.10.11+1b8db63b3) (1.3.3)
  |searxng| Collecting redis==5.0.8 (from searxng==2024.10.11+1b8db63b3)
  |searxng|   Downloading redis-5.0.8-py3-none-any.whl.metadata (9.2 kB)
  |searxng| Requirement already satisfied: markdown-it-py==3.0.0 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from searxng==2024.10.11+1b8db63b3) (3.0.0)
  |searxng| Requirement already satisfied: fasttext-predict==0.9.2.2 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from searxng==2024.10.11+1b8db63b3) (0.9.2.2)
  |searxng| Collecting pydantic==2.9.2 (from searxng==2024.10.11+1b8db63b3)
  |searxng|   Downloading pydantic-2.9.2-py3-none-any.whl.metadata (149 kB)
  |searxng| Collecting typer-slim==0.12.5 (from searxng==2024.10.11+1b8db63b3)
  |searxng|   Downloading typer_slim-0.12.5-py3-none-any.whl.metadata (15 kB)
  |searxng| Requirement already satisfied: pytomlpp==1.0.13 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from searxng==2024.10.11+1b8db63b3) (1.0.13)
  |searxng| Requirement already satisfied: Werkzeug>=3.0.0 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from flask==3.0.3->searxng==2024.10.11+1b8db63b3) (3.0.3)
  |searxng| Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from flask==3.0.3->searxng==2024.10.11+1b8db63b3) (2.1.2)
  |searxng| Requirement already satisfied: click>=8.1.3 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from flask==3.0.3->searxng==2024.10.11+1b8db63b3) (8.1.3)
  |searxng| Requirement already satisfied: blinker>=1.6.2 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from flask==3.0.3->searxng==2024.10.11+1b8db63b3) (1.6.2)
  |searxng| Requirement already satisfied: importlib-metadata>=3.6.0 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from flask==3.0.3->searxng==2024.10.11+1b8db63b3) (6.0.0)
  |searxng| Requirement already satisfied: pytz>=2022.7 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from flask-babel==4.0.0->searxng==2024.10.11+1b8db63b3) (2022.7)
  |searxng| Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from httpx==0.24.1->httpx[http2]==0.24.1->searxng==2024.10.11+1b8db63b3) (0.17.3)
  |searxng| Requirement already satisfied: idna in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from httpx==0.24.1->httpx[http2]==0.24.1->searxng==2024.10.11+1b8db63b3) (3.4)
  |searxng| Requirement already satisfied: sniffio in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from httpx==0.24.1->httpx[http2]==0.24.1->searxng==2024.10.11+1b8db63b3) (1.3.0)
  |searxng| Requirement already satisfied: python-socks>=2.0.0 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from httpx-socks==0.7.7->httpx-socks[asyncio]==0.7.7->searxng==2024.10.11+1b8db63b3) (2.1.1)
  |searxng| Requirement already satisfied: async-timeout>=3.0.1 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from httpx-socks[asyncio]==0.7.7->searxng==2024.10.11+1b8db63b3) (4.0.3)
  |searxng| Requirement already satisfied: h2<5,>=3 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from httpx[http2]==0.24.1->searxng==2024.10.11+1b8db63b3) (4.1.0)
  |searxng| Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from jinja2==3.1.4->searxng==2024.10.11+1b8db63b3) (2.1.1)
  |searxng| Requirement already satisfied: mdurl~=0.1 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from markdown-it-py==3.0.0->searxng==2024.10.11+1b8db63b3) (0.1.2)
  |searxng| Collecting annotated-types>=0.6.0 (from pydantic==2.9.2->searxng==2024.10.11+1b8db63b3)
  |searxng|   Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
  |searxng| Collecting pydantic-core==2.23.4 (from pydantic==2.9.2->searxng==2024.10.11+1b8db63b3)
  |searxng|   Downloading pydantic_core-2.23.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
  |searxng| Requirement already satisfied: typing-extensions>=4.6.1 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from pydantic==2.9.2->searxng==2024.10.11+1b8db63b3) (4.7.1)
  |searxng| Requirement already satisfied: six>=1.5 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from python-dateutil==2.9.0.post0->searxng==2024.10.11+1b8db63b3) (1.16.0)
  |searxng| Requirement already satisfied: hyperframe<7,>=6.0 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from h2<5,>=3->httpx[http2]==0.24.1->searxng==2024.10.11+1b8db63b3) (6.0.1)
  |searxng| Requirement already satisfied: hpack<5,>=4.0 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from h2<5,>=3->httpx[http2]==0.24.1->searxng==2024.10.11+1b8db63b3) (4.0.0)
  |searxng| Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from httpcore<0.18.0,>=0.15.0->httpx==0.24.1->httpx[http2]==0.24.1->searxng==2024.10.11+1b8db63b3) (0.14.0)
  |searxng| Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from httpcore<0.18.0,>=0.15.0->httpx==0.24.1->httpx[http2]==0.24.1->searxng==2024.10.11+1b8db63b3) (3.6.2)
  |searxng| Requirement already satisfied: zipp>=0.5 in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (from importlib-metadata>=3.6.0->flask==3.0.3->searxng==2024.10.11+1b8db63b3) (3.11.0)
  |searxng| Downloading babel-2.16.0-py3-none-any.whl (9.6 MB)
  |searxng|    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 57.1 MB/s eta 0:00:00
  |searxng| Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
  |searxng| Downloading lxml-5.3.0-cp39-cp39-manylinux_2_28_x86_64.whl (5.0 MB)
  |searxng|    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 86.2 MB/s eta 0:00:00
  |searxng| Downloading pydantic-2.9.2-py3-none-any.whl (434 kB)
  |searxng| Downloading redis-5.0.8-py3-none-any.whl (255 kB)
  |searxng| Downloading typer_slim-0.12.5-py3-none-any.whl (47 kB)
  |searxng| Downloading uvloop-0.20.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.5 MB)
  |searxng|    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 80.3 MB/s eta 0:00:00
  |searxng| Downloading pydantic_core-2.23.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
  |searxng|    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 77.3 MB/s eta 0:00:00
  |searxng| Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
  |searxng| Installing collected packages: uvloop, typer-slim, redis, pydantic-core, lxml, certifi, babel, annotated-types, pydantic, searxng
  |searxng|   Attempting uninstall: uvloop
  |searxng|     Found existing installation: uvloop 0.19.0
  |searxng|     Uninstalling uvloop-0.19.0:
  |searxng|       Successfully uninstalled uvloop-0.19.0
  |searxng|   Attempting uninstall: redis
  |searxng|     Found existing installation: redis 5.0.7
  |searxng|     Uninstalling redis-5.0.7:
  |searxng|       Successfully uninstalled redis-5.0.7
  |searxng|   Attempting uninstall: lxml
  |searxng|     Found existing installation: lxml 5.2.2
  |searxng|     Uninstalling lxml-5.2.2:
  |searxng|       Successfully uninstalled lxml-5.2.2
  |searxng|   Attempting uninstall: certifi
  |searxng|     Found existing installation: certifi 2024.7.4
  |searxng|     Uninstalling certifi-2024.7.4:
  |searxng|       Successfully uninstalled certifi-2024.7.4
  |searxng|   Attempting uninstall: babel
  |searxng|     Found existing installation: Babel 2.15.0
  |searxng|     Uninstalling Babel-2.15.0:
  |searxng|       Successfully uninstalled Babel-2.15.0
  |searxng|   Attempting uninstall: searxng
  |searxng|     Found existing installation: searxng 2024.7.20+657dcb973
  |searxng|     Uninstalling searxng-2024.7.20+657dcb973:
  |searxng|       Successfully uninstalled searxng-2024.7.20+657dcb973
  |searxng|   DEPRECATION: Legacy editable install of searxng==2024.10.11+1b8db63b3 from file:///usr/local/searxng/searxng-src (setup.py develop) is deprecated. pip 25.0 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
  |searxng|   Running setup.py develop for searxng
  |searxng| Successfully installed annotated-types-0.7.0 babel-2.16.0 certifi-2024.8.30 lxml-5.3.0 pydantic-2.9.2 pydantic-core-2.23.4 redis-5.0.8 searxng typer-slim-0.12.5 uvloop-0.20.0

update instance's settings.yml from /etc/searxng/settings.yml
INFO:  install (eval=0): /etc/searxng/settings.yml
INFO:  different file /etc/searxng/settings.yml already exists on this host
Menu::
  1.) replace file
  2.) leave file unchanged [default]
  3.) interactive shell
  4.) diff files
choose next step with file /etc/searxng/settings.yml [2] 

INFO:  restart uWSGI service
$ 
```

**Comment by return42** [comment]
pyyaml is installed twice, first as a prerequisite: 

https://github.com/searxng/searxng/blob/1b8db63b3351f39d5eded87d4226ea3289113472/utils/searxng.sh#L509-L510

```
pip install -U pyyaml
  |searxng| Requirement already satisfied: pip in /usr/local/searxng/searx-pyenv/lib/python3.9/site-packages (24.1.2)
  |searxng| Collecting pip
```

The following messages comes from the installed **2024.7.20+657dcb973**:

```
|searxng| ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
  |searxng| searxng 2024.7.20+657dcb973 requires pyyaml==6.0.1, but you have pyyaml 6.0.2 which is incompatible.
  |searxng| Successfully installed pyyaml-6.0.2
```

And the second installation comes from the `requirements.txt`:

https://github.com/searxng/searxng/blob/1b8db63b3351f39d5eded87d4226ea3289113472/requirements.txt#L9

https://github.com/searxng/searxng/blob/1b8db63b3351f39d5eded87d4226ea3289113472/utils/searxng.sh#L510-L511

In the code from above we see `pip install --use-pep517 --no-build-isolation -e .`  but you log says `pip install -U -e .`

```
pip install -U -e .
  |searxng| Installing collected packages: pip
  |searxng|   Attempting uninstall: pip
  |searxng|     Found existing installation: pip 24.1.2
  |searxng|     Uninstalling pip-24.1.2:
  |searxng|       Successfully uninstalled pip-24.1.2
  |searxng| Successfully installed pip-24.2
  ....
```

.. there is something wrong with your SearXNG clone; please login as `searxng` and check your active SearXNG clone `/usr/local/searxng/searxng-src`:

```
$ sudo -H -u searxng bash

[searxng@localhost]$ cd $HOME/searxng-src/
[searxng@localhost]$ pwd
/usr/local/searxng/searxng-src
[searxng@localhost]$ git fetch 
[searxng@localhost]$ git remote -v
origin	https://github.com/searxng/searxng (fetch)
origin	https://github.com/searxng/searxng (push)
[searxng@localhost]$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

[searxng@localhost]$ git log -10 --graph --oneline
...
```

**Comment by markmixx** [comment]
```
$ sudo -H -u searxng bash
searxng@searx:/home/markmixx$ cd $HOME/searxng-src/
searxng@searx:~/searxng-src$ pwd
/usr/local/searxng/searxng-src
searxng@searx:~/searxng-src$ git fetch
remote: Enumerating objects: 20958, done.
remote: Counting objects: 100% (2957/2957), done.
remote: Compressing objects: 100% (137/137), done.
remote: Total 20958 (delta 2374), reused 2924 (delta 2356), pack-reused 18001 (from 1)
Receiving objects: 100% (20958/20958), 12.83 MiB | 31.90 MiB/s, done.
Resolving deltas: 100% (6519/6519), completed with 377 local objects.
From https://github.com/searxng/searxng
   1b8db63b3..7e8b330b3  master                                                                        -> origin/master
 * [new branch]          dependabot/npm_and_yarn/searx/static/themes/simple/master/grunt-eslint-25.0.0 -> origin/dependabot/npm_and_yarn/searx/static/themes/simple/master/grunt-eslint-25.0.0
 * [new branch]          dependabot/pip/master/pylint-3.3.1                                            -> origin/dependabot/pip/master/pylint-3.3.1
 * [new branch]          dependabot/pip/master/redis-5.1.1                                             -> origin/dependabot/pip/master/redis-5.1.1
 * [new branch]          dependabot/pip/master/sphinx-8.1.0                                            -> origin/dependabot/pip/master/sphinx-8.1.0
 * [new branch]          dependabot/pip/master/sphinx-tabs-3.4.7                                       -> origin/dependabot/pip/master/sphinx-tabs-3.4.7
 * [new branch]          gh-pages                                                                      -> origin/gh-pages
 * [new branch]          translations                                                                  -> origin/translations
 * [new branch]          update_js_ariable_to_python                                                   -> origin/update_js_ariable_to_python
searxng@searx:~/searxng-src$ git remote -v
origin  https://github.com/searxng/searxng (fetch)
origin  https://github.com/searxng/searxng (push)
searxng@searx:~/searxng-src$ git status
On branch master
Your branch is behind 'origin/master' by 3 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean
searxng@searx:~/searxng-src$ git log -10 --graph --oneline
* 1b8db63b3 (HEAD -> master) [upd] pypi: Bump pydantic from 2.8.2 to 2.9.2
* 5a32ee410 [l10n] update translations from Weblate
* 81aaca8f4 [mod] use quad9 dns for connectivity checks when lxc
* f1f0dfd23 Revert "[fix] docker: alpine - install apk py3-pydantic-core"
* 5332d3a0b [fix] docker: alpine - install apk py3-pydantic-core
* f00fa76ed [build] /static
* a631f7740 [mod] favicons: simplify RTL in template & CSS
* a7d02d410 [doc] documentation of the favicons infrastructure
* 5ded9ada8 [mod] UI: add favicon's border- and background color to the definitons
* 7ab577a1f [mod] Revision of the favicon solution
searxng@searx:~/searxng-src$ 
```

**Comment by AlexanderS** [comment]
I think this issue only happens with python <3.11. https://github.com/searxng/searxng/blob/master/searx/compat.py imports the `tomli` module for older python versions, but I cannot find this anywhere in the `requirements.txt` or something like this.

I think we need something like:

```
tomli==2.0.2; python_version < '3.11'
```

in `requirements.txt`.

**Comment by return42** [comment]
> I think this issue only happens with python <3.11

@Alexander .. sure? .. 

> .. but I cannot find this anywhere in the `requirements.txt`

the name is `pytomlpp`:

https://github.com/searxng/searxng/blob/2986681b31a60d67e0468affb257a52246220f11/requirements.txt#L18

**Comment by AlexanderS** [comment]
`pytomlpp` also seems to be a toml python library, but is a different library then `tomli`. Maybe we can consolitdate the code to only require one toml implementation?

**Comment by return42** [comment]
Argh, my fail .. `tomli` is missed in the requirements.txt .. bugfix is on the way / thanks for pointing out :+1: 

The issue was not detected by unit tests since `tomli` was installed as a sub-requirement of black (which is only installed in the developer environment).

```
Collecting tomli>=1.1.0 (from black==24.3.0->-r /home/runner/work/searxng/searxng/requirements-dev.txt (line 4))
  Downloading tomli-2.0.2-py3-none-any.whl.metadata (10.0 kB)
```

**Comment by return42** [comment]
FYI: issue is fixed in https://github.com/searxng/searxng/pull/3926 .. your review is welcome :) / thanks :+1:

**Comment by LyndonArmitage** [comment]
Looks great!
