### ISSUE TITLE
Latest Docker container broken with error: unable to open database file

### ISSUE THREAD

**Issue by ad-on-is** [searxng/searxng#3943]
The latest Docker container seems broken, throwing an error that it's unable to open the sqlite database file.

<details><summary>Logs</summary>
<p>

````
2024-10-18 19:07:38,628 ERROR:searx.webapp: Exception on /search [GET]

Traceback (most recent call last):

  File "/usr/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app

    response = self.full_dispatch_request()

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request

    rv = self.handle_user_exception(e)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request

    rv = self.dispatch_request()

         ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/searxng/searx/webapp.py", line 776, in search

    return render(

           ^^^^^^^

  File "/usr/local/searxng/searx/webapp.py", line 468, in render

    result = render_template('{}/{}'.format(kwargs['theme'], template_name), **kwargs)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template

    return _render(app, template, context)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/flask/templating.py", line 131, in _render

    rv = template.render(context)

         ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render

    self.environment.handle_exception()

  File "/usr/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception

    raise rewrite_traceback_stack(source=source)

  File "/usr/local/searxng/searx/templates/simple/results.html", line 6, in top-level template code

    <input type="hidden" name="engine_data-{{ engine_name }}-{{ k|e }}" value="{{ v|e }}">

    ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/searxng/searx/templates/simple/base.html", line 63, in top-level template code

    {% block content %}

  File "/usr/local/searxng/searx/templates/simple/results.html", line 99, in block 'content'

    {% include get_result_template('simple', result['template']) %}

    ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/searxng/searx/templates/simple/result_templates/default.html", line 3, in top-level template code

    {{ result_header(result, favicons, image_proxify) -}}

    ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.12/site-packages/jinja2/runtime.py", line 782, in _invoke

    rv = self._func(*arguments)

         ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/searxng/searx/templates/simple/macros.html", line 25, in template

    <div class="favicon"><img loading="lazy" src="{{ favicon_url(result.parsed_url.netloc) }}"></div>

    ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/searxng/searx/favicons/proxy.py", line 223, in favicon_url

    data_mime = cache.CACHE(resolver, authority)

                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/searxng/searx/favicons/cache.py", line 315, in __call__

    res = self.DB.execute(sql, (resolver, authority)).fetchone()

          ^^^^^^^

  File "/usr/local/searxng/searx/sqlitedb.py", line 172, in DB

    self.thread_local.DB = self.connect()

                           ^^^^^^^^^^^^^^

  File "/usr/local/searxng/searx/sqlitedb.py", line 124, in connect

    self.init()

  File "/usr/local/searxng/searx/sqlitedb.py", line 202, in init

    self.properties.init()

  File "/usr/local/searxng/searx/sqlitedb.py", line 277, in init

    with self.DB as conn:

         ^^^^^^^

  File "/usr/local/searxng/searx/sqlitedb.py", line 172, in DB

    self.thread_local.DB = self.connect()

                           ^^^^^^^^^^^^^^

  File "/usr/local/searxng/searx/sqlitedb.py", line 126, in connect

    conn = sqlite3.Connection(self.db_url, **self.SQLITE_CONNECT_ARGS)  # type: ignore

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

sqlite3.OperationalError: unable to open database file
````

</p>
</details>

**Comment by baskinsy** [comment]
Works for me. Did you enabled favicons?

**Comment by ad-on-is** [comment]
> Works for me. Did you enabled favicons?

Yes I did.

**Comment by baskinsy** [comment]
I had the same issue when I was using a docker volume for the cache and also when I mount a local folder (like the /etc/searxg) mount. After changing the permission on the cache path to 777, it worked.

**Comment by ad-on-is** [comment]
I followed the guide here: https://docs.searxng.org/admin/searx.favicons.html

Setting a custom db_url results in the error, despite having 777 on the file. So it can only be mapped to /tmp/faviconcache.db.
