### ISSUE TITLE
Internal server error after last update

### ISSUE THREAD

**Issue by ghost** [searxng/searxng#3977]
Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG

commit https://github.com/searxng/searxng/commit/fa4dfd4efea01d558dd4c8b0d6db39708ee03917

How did you install SearXNG?

Installation script

What happened?

I ran the update script twice, without replacing settings.yml and replacing settings.yml and both SearxNG reports “Internal server error.”

How To Reproduce
Update Searxng

Expected behavior
The application is updated correctly

Screenshots & Logs

```
Update SearXNG instance
=======================

fetch from https://github.com/searxng/searxng and reset to origin/master
cd /usr/local/searxng/searxng-src
git fetch origin "master"
git reset --hard "origin/master"
pip install -U pip
  |searxng| Depuis https://github.com/searxng/searxng
  |searxng|  * branch                master     -> FETCH_HEAD
  |searxng| HEAD est maintenant à fa4dfd4ef [fix] favicons: msgspec.ValidationError: Expected `Path`, got `str` - at `$.favicons.cache.db_url`
pip install -U setuptools
  |searxng| Traceback (most recent call last):
  |searxng|   File "/usr/local/searxng/searx-pyenv/bin/pip", line 8, in <module>
  |searxng|     sys.exit(main())
  |searxng|              ^^^^^^
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/cli/main.py", line 78, in main
  |searxng|     command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  |searxng|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/commands/__init__.py", line 114, in create_command
  |searxng|     module = importlib.import_module(module_path)
  |searxng|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |searxng|   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
  |searxng|     return _bootstrap._gcd_import(name[level:], package, level)
  |searxng|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |searxng|   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  |searxng|   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  |searxng|   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  |searxng|   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  |searxng|   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  |searxng|   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 16, in <module>
  |searxng|     from pip._internal.cli.req_command import (
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 18, in <module>
  |searxng|     from pip._internal.index.collector import LinkCollector
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/index/collector.py", line 38, in <module>
  |searxng|     from pip._internal.network.session import PipSession
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/network/session.py", line 33, in <module>
  |searxng|     from pip._vendor.cachecontrol import CacheControlAdapter as _BaseCacheControlAdapter
  |searxng| ModuleNotFoundError: No module named 'pip._vendor.cachecontrol'
pip install -U wheel
  |searxng| Traceback (most recent call last):
  |searxng|   File "/usr/local/searxng/searx-pyenv/bin/pip", line 8, in <module>
  |searxng|     sys.exit(main())
  |searxng|              ^^^^^^
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/cli/main.py", line 78, in main
  |searxng|     command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  |searxng|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/commands/__init__.py", line 114, in create_command
  |searxng|     module = importlib.import_module(module_path)
  |searxng|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |searxng|   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
  |searxng|     return _bootstrap._gcd_import(name[level:], package, level)
  |searxng|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |searxng|   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  |searxng|   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  |searxng|   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  |searxng|   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  |searxng|   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  |searxng|   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 16, in <module>
  |searxng|     from pip._internal.cli.req_command import (
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 18, in <module>
  |searxng|     from pip._internal.index.collector import LinkCollector
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/index/collector.py", line 38, in <module>
  |searxng|     from pip._internal.network.session import PipSession
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/network/session.py", line 33, in <module>
  |searxng|     from pip._vendor.cachecontrol import CacheControlAdapter as _BaseCacheControlAdapter
  |searxng| ModuleNotFoundError: No module named 'pip._vendor.cachecontrol'
pip install -U pyyaml
pip install -U --use-pep517 --no-build-isolation -e .
  |searxng| Traceback (most recent call last):
  |searxng|   File "/usr/local/searxng/searx-pyenv/bin/pip", line 8, in <module>
  |searxng|     sys.exit(main())
  |searxng|              ^^^^^^
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/cli/main.py", line 78, in main
  |searxng|     command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  |searxng|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/commands/__init__.py", line 114, in create_command
  |searxng|     module = importlib.import_module(module_path)
  |searxng|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |searxng|   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
  |searxng|     return _bootstrap._gcd_import(name[level:], package, level)
  |searxng|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |searxng|   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  |searxng|   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  |searxng|   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  |searxng|   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  |searxng|   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  |searxng|   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 16, in <module>
  |searxng|     from pip._internal.cli.req_command import (
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 18, in <module>
  |searxng|     from pip._internal.index.collector import LinkCollector
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/index/collector.py", line 38, in <module>
  |searxng|     from pip._internal.network.session import PipSession
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/network/session.py", line 33, in <module>
  |searxng|     from pip._vendor.cachecontrol import CacheControlAdapter as _BaseCacheControlAdapter
  |searxng| ModuleNotFoundError: No module named 'pip._vendor.cachecontrol'
  |searxng| Traceback (most recent call last):
  |searxng|   File "/usr/local/searxng/searx-pyenv/bin/pip", line 8, in <module>
  |searxng|     sys.exit(main())
  |searxng|              ^^^^^^
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/cli/main.py", line 78, in main
  |searxng|     command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  |searxng|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/commands/__init__.py", line 114, in create_command
  |searxng|     module = importlib.import_module(module_path)
  |searxng|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |searxng|   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
  |searxng|     return _bootstrap._gcd_import(name[level:], package, level)
  |searxng|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |searxng|   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  |searxng|   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  |searxng|   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  |searxng|   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  |searxng|   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  |searxng|   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 16, in <module>
  |searxng|     from pip._internal.cli.req_command import (
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 18, in <module>
  |searxng|     from pip._internal.index.collector import LinkCollector
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/index/collector.py", line 38, in <module>
  |searxng|     from pip._internal.network.session import PipSession
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/network/session.py", line 33, in <module>
  |searxng|     from pip._vendor.cachecontrol import CacheControlAdapter as _BaseCacheControlAdapter
  |searxng| ModuleNotFoundError: No module named 'pip._vendor.cachecontrol'
  |searxng| Traceback (most recent call last):
  |searxng|   File "/usr/local/searxng/searx-pyenv/bin/pip", line 8, in <module>
  |searxng|     sys.exit(main())
  |searxng|              ^^^^^^
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/cli/main.py", line 78, in main
  |searxng|     command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  |searxng|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/commands/__init__.py", line 114, in create_command
  |searxng|     module = importlib.import_module(module_path)
  |searxng|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |searxng|   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
  |searxng|     return _bootstrap._gcd_import(name[level:], package, level)
  |searxng|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |searxng|   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  |searxng|   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  |searxng|   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  |searxng|   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  |searxng|   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  |searxng|   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 16, in <module>
  |searxng|     from pip._internal.cli.req_command import (
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 18, in <module>
  |searxng|     from pip._internal.index.collector import LinkCollector
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/index/collector.py", line 38, in <module>
  |searxng|     from pip._internal.network.session import PipSession
  |searxng|   File "/usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/pip/_internal/network/session.py", line 33, in <module>
  |searxng|     from pip._vendor.cachecontrol import CacheControlAdapter as _BaseCacheControlAdapter
  |searxng| ModuleNotFoundError: No module named 'pip._vendor.cachecontrol'

update instance's settings.yml from /etc/searxng/settings.yml
INFO:  install (eval=0): /etc/searxng/settings.yml
INFO:  different file /etc/searxng/settings.yml already exists on this host
Menu::
  1.) replace file
  2.) leave file unchanged [default]
  3.) interactive shell
  4.) diff files
choose next step with file /etc/searxng/settings.yml [2] 1
INFO:  restart uWSGI service
```

**Comment by unixfox** [comment]
Please update this has been fixed yesterday: https://github.com/searxng/searxng/issues/3975#issuecomment-2444910833

**Comment by ghost** [comment]
I just did, I'm not on docker.
Still not working .

**Comment by ghost** [comment]
When on process to update many times, not working and always throws Internal server error so ..
better to say I did :
sudo -H /usr/local/searxng/searxng-src/utils/searxng.sh remove all
then make the whole process to install again
now this is working

**Comment by return42** [comment]
As @unixfox pointed out ...

```
HEAD est maintenant à fa4dfd4ef [fix] favicons: msgspec.ValidationError: Expected `Path`, got `str` - at `$.favicons.cache.db_url`
```

... has been fixed yesterday.  It may be that something got stuck during the updates ... a new installation is then the simplest solution.

Many thanks for your solution :+1:

**Comment by ghost** [comment]
You're welcome
I guess you are right, even after I reverted lines on the two last committed files from fa4dfd4ef it didn't work.
Anyway fantastic work all of you
