### ISSUE TITLE
CI often fails for no reason

### ISSUE THREAD

**Issue by return42** [searxng/searxng#3983]
In the CI log in 9 / 10 fails we see that the unit test is passed (OK) and the coverage process ends with an exit code (2). --> after a "Re-Run all failed jobs" the jobs are passed without any fail (in a second or third attempt !?!). 

```
./manage test.unit
INFO:  sourced NVM environment from /home/runner/.nvm
TEST      tests/unit

Ran 286 tests in 2.483s
... 
OK
...
./manage test.coverage
INFO:  sourced NVM environment from /home/runner/.nvm
TEST      unit test coverage
...
======================================================================
FAIL: test_localized_query_07_1_0_1_0 (tests.unit.test_plugin_calculator.PluginCalculator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/searxng/searxng/local/py3/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func
    return func(*(a + p.args), **p.kwargs, **kw)
  File "/home/runner/work/searxng/searxng/tests/unit/test_plugin_calculator.py", line 88, in test_localized_query
    self.assertIn('calculate', search.result_container.answers)
AssertionError: 'calculate' not found in {}

...
ERROR: test.coverage exit with error (1)
make: *** [Makefile:94: test.coverage] Error 1
Error: Process completed with exit code 2.
```

When building make target `test.coverage` on a local machine, the last line in the LOG is:

```
Wrote HTML report to file:///share/searxng/coverage/index.htmlcoverage/index.html
```

The absence of this message suggests that the coverage test in the CI has problems writing the file, which in turn suggests that this problem is related to the upload-artifact@v3  action (BTW v3 is deprecated):

https://github.com/searxng/searxng/blob/cc148a76b0abb91986db5b1183458d636face5e3/.github/workflows/integration.yml#L48-L55

--------------

Another issue often seen in the CI (but never seen in a local run) is a segmentation fault:

```
./manage test.unit
INFO:  sourced NVM environment from /home/runner/.nvm
TEST      tests/unit
PYENV     [check] import yaml --> OK
PYENV     OK
+ local/py3/bin/python -c 'import sys; sys.path.pop(0); import  searx ;'
+ python -m nose2 -s tests/unit
ERROR:searx:Error while getting the git URL & branch: fatal: no such branch: 'master'

CRITICAL:searx.favicons.cache:Disable favicon caching completely: SQLite library (3.31.1) is too old! (require >= 3.35)
................................................................CRITICAL:searx.favicons.cache:Disable favicon caching completely: SQLite library (3.31.1) is too old! (require >= 3.35)
.......................................ERROR:searx.engines.tineye:HTTP Status Code: 400
.WARNING:searx.engines.tineye:Unknown suggestion key encountered: 
ERROR:searx.engines.tineye:HTTP Status Code: 422
......................................................................................................................................................................................
----------------------------------------------------------------------
Ran 286 tests in 2.777s

OK
./utils/lib.sh: line 726:  5389 Segmentation fault      (core dumped) "$@"
```

https://github.com/searxng/searxng/blob/cc148a76b0abb91986db5b1183458d636face5e3/utils/lib.sh#L719-L727

The command `python -m nose2 -s tests/unit` is executed in line 725 by `"$@"`.  Which suggests that the nose2 test causes a memory error in the CI (only ?!?).

**Comment by return42** [comment]
The unit tests have been completely revised, see chapter [Unit-Tests](https://github.com/searxng/searxng/pull/4183). Since #4183 had been merged these problems have not occurred again.
