### ISSUE TITLE
go back to localhost after Preferences configure

### ISSUE THREAD

**Issue by herman1114** [searxng/searxng#4012]
searxNG is a very good project and has been tried for a day, but some bugs may need to be fixed.

Bug : After completing perference and save. will go back localhost

The environment is as follows:
1. install docer:latest  version
2. os : casaos
. 
error log :
main_app-1  | 2024-11-14 10:23:32,848 ERROR:searx.engines.wikidata: Fail to initialize
main_app-1  | Traceback (most recent call last):
main_app-1  |   File "/usr/local/searxng/searx/network/__init__.py", line 95, in request
main_app-1  |     return future.result(timeout)
main_app-1  |            ^^^^^^^^^^^^^^^^^^^^^^
main_app-1  |   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 458, in result
main_app-1  |     raise TimeoutError()
main_app-1  | TimeoutError
main_app-1  | 
main_app-1  | The above exception was the direct cause of the following exception:
main_app-1  | 
main_app-1  | Traceback (most recent call last):
main_app-1  |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 73, in initialize
main_app-1  |     self.engine.init(get_engine_from_settings(self.engine_name))
main_app-1  |   File "/usr/local/searxng/searx/engines/wikidata.py", line 775, in init
main_app-1  |     jsonresponse = send_wikidata_query(query)
main_app-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
main_app-1  |   File "/usr/local/searxng/searx/engines/wikidata.py", line 161, in send_wikidata_query
main_app-1  |     http_response = get(SPARQL_ENDPOINT_URL + '?' + urlencode({'query': query}), headers=get_headers())
main_app-1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
main_app-1  |   File "/usr/local/searxng/searx/network/__init__.py", line 164, in get
main_app-1  |     return request('get', url, **kwargs)
main_app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
main_app-1  |   File "/usr/local/searxng/searx/network/__init__.py", line 97, in request
main_app-1  |     raise httpx.TimeoutException('Timeout', request=None) from e
main_app-1  | httpx.TimeoutException: Timeout
main_app-1  | 2024-11-14 10:23:33,239 ERROR:searx.engines.wikidata: Fail to initialize
main_app-1  | Traceback (most recent call last):
main_app-1  |   File "/usr/local/searxng/searx/network/__init__.py", line 95, in request
main_app-1  |     return future.result(timeout)
main_app-1  |            ^^^^^^^^^^^^^^^^^^^^^^
main_app-1  |   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 458, in result
main_app-1  |     raise TimeoutError()
main_app-1  | TimeoutError
main_app-1  | 
main_app-1  | The above exception was the direct cause of the following exception:
main_app-1  | 
main_app-1  | Traceback (most recent call last):
main_app-1  |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 73, in initialize
main_app-1  |     self.engine.init(get_engine_from_settings(self.engine_name))
main_app-1  |   File "/usr/local/searxng/searx/engines/wikidata.py", line 775, in init
main_app-1  |     jsonresponse = send_wikidata_query(query)
main_app-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
main_app-1  |   File "/usr/local/searxng/searx/engines/wikidata.py", line 161, in send_wikidata_query
main_app-1  |     http_response = get(SPARQL_ENDPOINT_URL + '?' + urlencode({'query': query}), headers=get_headers())
main_app-1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
main_app-1  |   File "/usr/local/searxng/searx/network/__init__.py", line 164, in get
main_app-1  |     return request('get', url, **kwargs)
main_app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
main_app-1  |   File "/usr/local/searxng/searx/network/__init__.py", line 97, in request
main_app-1  |     raise httpx.TimeoutException('Timeout', request=None) from e
main_app-1  | httpx.TimeoutException: Timeout
main_app-1  | 2024-11-14 10:23:32,761 ERROR:searx.engines.wikidata: Fail to initialize
main_app-1  | Traceback (most recent call last):
main_app-1  |   File "/usr/local/searxng/searx/network/__init__.py", line 95, in request
main_app-1  |     return future.result(timeout)
main_app-1  |            ^^^^^^^^^^^^^^^^^^^^^^
main_app-1  |   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 458, in result
main_app-1  |     raise TimeoutError()
main_app-1  | TimeoutError
main_app-1  | 
main_app-1  | The above exception was the direct cause of the following exception:
main_app-1  | 
main_app-1  | Traceback (most recent call last):
main_app-1  |   File "/usr/local/searxng/searx/search/processors/abstract.py", line 73, in initialize
main_app-1  |     self.engine.init(get_engine_from_settings(self.engine_name))
main_app-1  |   File "/usr/local/searxng/searx/engines/wikidata.py", line 775, in init
main_app-1  |     jsonresponse = send_wikidata_query(query)
main_app-1  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
main_app-1  |   File "/usr/local/searxng/searx/engines/wikidata.py", line 161, in send_wikidata_query
main_app-1  |     http_response = get(SPARQL_ENDPOINT_URL + '?' + urlencode({'query': query}), headers=get_headers())
main_app-1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
main_app-1  |   File "/usr/local/searxng/searx/network/__init__.py", line 164, in get
main_app-1  |     return request('get', url, **kwargs)
main_app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
main_app-1  |   File "/usr/local/searxng/searx/network/__init__.py", line 97, in request
main_app-1  |     raise httpx.TimeoutException('Timeout', request=None) from e
main_app-1  | httpx.TimeoutException: Timeout
main_app-1  | Thu Nov 14 10:23:33 2024 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
main_app-1  | Thu Nov 14 10:23:33 2024 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 341] during GET /preferences (192.168.88.88)
main_app-1  | OSError: write error

**Comment by herman1114** [comment]
sorry, fix retuen to localhost by edit setting.yaml
...still error report
