### ISSUE TITLE
Bug: yep engine / SearxEngineAccessDeniedException

### ISSUE THREAD

**Issue by return42** [searxng/searxng#4037]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.11.23+7c4e4ebd4+dirty

**How did you install SearXNG?**

    make run

**How To Reproduce**

Query `!yep berlin` returns HTTP 403 (Forbidden), but when I open the generated URL

  https://api.yep.com/fs/2/search?client=web&no_correct=false&q=berlin&safeSearch=off&type=web

in my browser I get a valid JSON response.

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:116`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

```
WARNING searx.network.yep             : HTTP Request failed: GET https://api.yep.com/fs/2/search?client=web&no_correct=false&q=berlin&safeSearch=off&type=web
WARNING searx.engines.yep             : ErrorContext('searx/search/processors/online.py', 116, "response = req(params['url'], **request_args)", 'searx.exceptions.SearxEngineAccessDeniedException', None, ('HTTP error 403',)) False
DEBUG   searx.searx.search.processor  : Suspend for 86400 seconds
ERROR   searx.engines.yep             : SearXNG is blocked
Traceback (most recent call last):
  File "/share/searxng/searx/search/processors/online.py", line 160, in search
    search_results = self._search_basic(query, params)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/searxng/searx/search/processors/online.py", line 144, in _search_basic
    response = self._send_http_request(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/searxng/searx/search/processors/online.py", line 116, in _send_http_request
    response = req(params['url'], **request_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/searxng/searx/network/__init__.py", line 164, in get
    return request('get', url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/searxng/searx/network/__init__.py", line 95, in request
    return future.result(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/markus/.asdf/installs/python/3.12.0/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/markus/.asdf/installs/python/3.12.0/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/share/searxng/searx/network/network.py", line 291, in request
    return await self.call_client(False, method, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/searxng/searx/network/network.py", line 274, in call_client
    return self.patch_response(response, do_raise_for_httperror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/searxng/searx/network/network.py", line 245, in patch_response
    raise_for_httperror(response)
  File "/share/searxng/searx/network/raise_for_httperror.py", line 74, in raise_for_httperror
    raise SearxEngineAccessDeniedException(message='HTTP error ' + str(resp.status_code))
searx.exceptions.SearxEngineAccessDeniedException: HTTP error 403, suspended_time=86400
```

**Comment by return42** [comment]
When using curl, a "you are blocked / CAPTCHA" is in the response (see ``Cloudflare Ray ID`` below):

```
$ curl --http3-only 'https://api.yep.com/fs/2/search?client=web&no_correct=false&q=berlin&safeSearch=off&type=web' 
...
<head>
<title>Attention Required! | Cloudflare</title>
...
</head>
<body>
...
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> yep.com</h2>
      </div><!-- /.header -->

      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">
            
              <span class="cf-no-screenshot error"></span>
            
          </div>
        </div>
      </div><!-- /.captcha-container -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>

            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>

            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the 

Cloudflare Ray ID found at the bottom of this page.</p>
...
```

**Comment by Bnyro** [comment]
Seems to happen even when passing valid session cookies, I don't think we can do much about these Cloudflare checks :disappointed:

**Comment by return42** [comment]
Hm, but why do https://api.yep.com/fs/2/search?client=web&no_correct=false&q=berlin&safeSearch=off&type=web get a response in the browser?

**Comment by Bnyro** [comment]
Possibly some kind of TLS fingerprinting? I've seen Reddit doing that a lot recently.

**Comment by Austin-Olacsi** [comment]
i made a bug report for this last summer in https://github.com/searxng/searxng/issues/3589

for now, i depend on another service to have this engine https://github.com/searxng/searxng/pull/3401

a fix for this issue is also likely to fix https://github.com/searxng/searxng/issues/3068
