### ISSUE TITLE
Bug: pypi engine

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#4093]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2024.11.22+67f754857

**How did you install SearXNG?**

Docker image

**What happened?**

Any search leads to a parsing error ( `!pypi lxml` for example).

**How To Reproduce**

see above

**Expected behavior**

engine works

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineXPathException
  * Percentage: 35
  * Parameters: `('./h3/span[@class="package-snippet__version"]', 'index 0 not found')`
  * File name: `searx/engines/pypi.py:50`
  * Function: `response`
  * Code: `version = extract_text(eval_xpath_getindex(entry, './h3/span[@class="package-snippet__version"]', 0))`

**Comment by Bnyro** [comment]
When you initially open the website without a session cookie set, you get to a Fastly page with some JavaScript that generates a session cookie, sets it and reloads the page (JavaScript must be disabled to test it).

It's unlikely that we can figure out how to generate session cookies ourselves...

**Comment by dalf** [comment]
I've seen that, but pip/uv work.

* <https://pypi.org/simple/>
* <https://pypi.org/pypi/fasttext-predict/json> (for example)

I'm not sure how to make an engine from that.

Perhaps using https://github.com/searxng/searxng/blob/3742d558ac5fe756a62632fdbdf84f0d3ddb7de2/searx/network/__init__.py#L100C5-L100C19 ?

**Comment by return42** [comment]
Thats really annoying ..  XML-RPC search is no longer supported and all query tools are broken:

```
$ pypi-search flask
[INFO] :: Searching for package `flask`...
Traceback (most recent call last):
  File "/tmp/env/bin/pypi-search", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/tmp/env/lib/python3.13/site-packages/pypi_search/main.py", line 35, in main
    version_info = pypi.get_version_info()
  File "/tmp/env/lib/python3.13/site-packages/pypi_search/utils.py", line 41, in get_version_info
    version_no = package_name_header.text.split()[1]
                 ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
```

and once again typical for the Python ecosystem: even standard tools like pip are not considered ... I've been using Python for 25 years (a quarter of a century!?!) and Python still can't get consistent and convenient package management (which npm has had since day one) ... a tragedy ... sorry, but I'm really frustrated right now.

```
$ pip search flask
ERROR: XMLRPC request failed [code: -32500]
RuntimeError: PyPI no longer supports 'pip search' (or XML-RPC search). Please use https://pypi.org/search (via a browser) instead. See https://warehouse.pypa.io/api-reference/xml-rpc.html#deprecated-methods for more information.
```

**Comment by return42** [comment]
Apparently I'm not the first person to think about simply reading all the endpoints of the PyPi API and building my own database --> https://pypicache.repology.org/

Unpacked the JSON file is > 1.4GB ... here an exemplary excerpt of an element: 

```json
{
  "info": {
    "author": null,
    "author_email": "Toshio Kuratomi <a.badger@gmail.com>, Felix Fontein <felix@fontein.de>",
    "bugtrack_url": null,
    "classifiers": [
      "Development Status :: 5 - Production/Stable",
      "Framework :: Ansible",
      "Intended Audience :: Developers",
      "Programming Language :: Python :: 3.10",
      "Programming Language :: Python :: 3.11",
      "Programming Language :: Python :: 3.12",
      "Programming Language :: Python :: 3.13",
      "Programming Language :: Python :: 3.9",
      "Typing :: Typed"
    ],
    "description_content_type": "text/markdown",
    "docs_url": null,
    "download_url": null,
    "downloads": {
      "last_day": -1,
      "last_month": -1,
      "last_week": -1
    },
    "dynamic": null,
    "home_page": null,
    "keywords": null,
    "license": null,
    "license_expression": "GPL-3.0-or-later AND Python-2.0.1",
    "license_files": [
      "LICENSES/GPL-3.0-or-later.txt",
      "LICENSES/Python-2.0.1.txt"
    ],
    "maintainer": null,
    "maintainer_email": "Felix Fontein <felix@fontein.de>, Maxwell G <maxwell@gtmx.me>",
    "name": "antsibull-build",
    "package_url": "https://pypi.org/project/antsibull-build/",
    "platform": null,
    "project_url": "https://pypi.org/project/antsibull-build/",
    "project_urls": {
      "Bug tracker": "https://github.com/ansible-community/antsibull-build/issues",
      "Changelog": "https://github.com/ansible-community/antsibull-build/tree/main/CHANGELOG.md",
      "Code of Conduct": "https://docs.ansible.com/ansible/latest/community/code_of_conduct.html",
      "Source code": "https://github.com/ansible-community/antsibull-build"
    },
    "provides_extra": [
      "all",
      "clipboard",
      "codeqa",
      "coverage",
      "dev",
      "formatters",
      "test",
      "typing"
    ],
    "release_url": "https://pypi.org/project/antsibull-build/0.72.3/",
    "requires_dist": [
      "aiofiles",
      "aiohttp>=3.0.0",
      "antsibull-changelog>=0.31.0",
      "antsibull-core<4.0.0,>=3.4.0",
      "antsibull-docs-parser<2.0.0,>=1.1.0",
      "antsibull-fileutils<2.0.0,>=1.0.0",
      "asyncio-pool",
      "build",
      "jinja2",
      "packaging>=20.0",
      "pydantic<3,>=2",
      "pyyaml",
      "semantic-version",
      "twiggy",
      "typing-extensions",
      "pyperclip; extra == \"all\"",
      "pyperclip; extra == \"clipboard\"",
      "flake8>=3.8.0; extra == \"codeqa\"",
      "pylint; extra == \"codeqa\"",
      "reuse; extra == \"codeqa\"",
      "coverage[toml]; extra == \"coverage\"",
      "asynctest; extra == \"dev\"",
      "coverage[toml]; extra == \"dev\"",
      "cryptography; extra == \"dev\"",
      "flake8>=3.8.0; extra == \"dev\"",
      "mypy; extra == \"dev\"",
      "nox; extra == \"dev\"",
      "pylint; extra == \"dev\"",
      "pyperclip; extra == \"dev\"",
      "pytest; extra == \"dev\"",
      "pytest-asyncio>=0.12; extra == \"dev\"",
      "pytest-cov; extra == \"dev\"",
      "pytest-error-for-skips; extra == \"dev\"",
      "reuse; extra == \"dev\"",
      "types-aiofiles; extra == \"dev\"",
      "types-docutils; extra == \"dev\"",
      "types-pyyaml; extra == \"dev\"",
      "types-setuptools; extra == \"dev\"",
      "black>=24; extra == \"formatters\"",
      "isort; extra == \"formatters\"",
      "asynctest; extra == \"test\"",
      "cryptography; extra == \"test\"",
      "pytest; extra == \"test\"",
      "pytest-asyncio>=0.12; extra == \"test\"",
      "pytest-cov; extra == \"test\"",
      "pytest-error-for-skips; extra == \"test\"",
      "mypy; extra == \"typing\"",
      "pytest; extra == \"typing\"",
      "types-aiofiles; extra == \"typing\"",
      "types-docutils; extra == \"typing\"",
      "types-pyyaml; extra == \"typing\"",
      "types-setuptools; extra == \"typing\""
    ],
    "requires_python": ">=3.9",
    "summary": "Tools for building the Ansible Distribution",
    "version": "0.72.3",
    "yanked": false,
    "yanked_reason": null
  },
  "last_serial": 28561230,
  "releases": {
    "0.72.3": [
      {
        "comment_text": null,
        "digests": {
          "blake2b_256": "6312d2efc8a7b4819c702e2c90a97bf34af016ba98ff9ebe2c3ef45ce46e8261",
          "md5": "b6f28863a1d8a6a50cbe1fc4bbb85379",
          "sha256": "cf9136b028bc8dd083fa40798212ec2eddddce57c1f40353ba1803d0101e3831"
        },
        "downloads": -1,
        "filename": "antsibull_build-0.72.3-py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "b6f28863a1d8a6a50cbe1fc4bbb85379",
        "packagetype": "bdist_wheel",
        "python_version": "py3",
        "requires_python": ">=3.9",
        "size": 119129,
        "upload_time": "2025-04-16T18:28:46",
        "upload_time_iso_8601": "2025-04-16T18:28:46.664150Z",
        "url": "https://files.pythonhosted.org/packages/63/12/d2efc8a7b4819c702e2c90a97bf34af016ba98ff9ebe2c3ef45ce46e8261/antsibull_build-0.72.3-py3-none-any.whl",
        "yanked": false,
        "yanked_reason": null
      },
      {
        "comment_text": null,
        "digests": {
          "blake2b_256": "84305d010d1f3d7ff8e3c273041b0e0e65acb54275d5df6b990367fca4db7a2b",
          "md5": "2ae5594cf91bdace84c1a809a7354222",
          "sha256": "f39f603e758d07c9e23a5f981d7fdf4ec21033a50b8d9622669742bd29ef6e4a"
        },
        "downloads": -1,
        "filename": "antsibull_build-0.72.3.tar.gz",
        "has_sig": false,
        "md5_digest": "2ae5594cf91bdace84c1a809a7354222",
        "packagetype": "sdist",
        "python_version": "source",
        "requires_python": ">=3.9",
        "size": 1378425,
        "upload_time": "2025-04-16T18:28:50",
        "upload_time_iso_8601": "2025-04-16T18:28:50.203475Z",
        "url": "https://files.pythonhosted.org/packages/84/30/5d010d1f3d7ff8e3c273041b0e0e65acb54275d5df6b990367fca4db7a2b/antsibull_build-0.72.3.tar.gz",
        "yanked": false,
        "yanked_reason": null
      }
    ]
  },
  "urls": [
    {
      "comment_text": null,
      "digests": {
        "blake2b_256": "6312d2efc8a7b4819c702e2c90a97bf34af016ba98ff9ebe2c3ef45ce46e8261",
        "md5": "b6f28863a1d8a6a50cbe1fc4bbb85379",
        "sha256": "cf9136b028bc8dd083fa40798212ec2eddddce57c1f40353ba1803d0101e3831"
      },
      "downloads": -1,
      "filename": "antsibull_build-0.72.3-py3-none-any.whl",
      "has_sig": false,
      "md5_digest": "b6f28863a1d8a6a50cbe1fc4bbb85379",
      "packagetype": "bdist_wheel",
      "python_version": "py3",
      "requires_python": ">=3.9",
      "size": 119129,
      "upload_time": "2025-04-16T18:28:46",
      "upload_time_iso_8601": "2025-04-16T18:28:46.664150Z",
      "url": "https://files.pythonhosted.org/packages/63/12/d2efc8a7b4819c702e2c90a97bf34af016ba98ff9ebe2c3ef45ce46e8261/antsibull_build-0.72.3-py3-none-any.whl",
      "yanked": false,
      "yanked_reason": null
    },
    {
      "comment_text": null,
      "digests": {
        "blake2b_256": "84305d010d1f3d7ff8e3c273041b0e0e65acb54275d5df6b990367fca4db7a2b",
        "md5": "2ae5594cf91bdace84c1a809a7354222",
        "sha256": "f39f603e758d07c9e23a5f981d7fdf4ec21033a50b8d9622669742bd29ef6e4a"
      },
      "downloads": -1,
      "filename": "antsibull_build-0.72.3.tar.gz",
      "has_sig": false,
      "md5_digest": "2ae5594cf91bdace84c1a809a7354222",
      "packagetype": "sdist",
      "python_version": "source",
      "requires_python": ">=3.9",
      "size": 1378425,
      "upload_time": "2025-04-16T18:28:50",
      "upload_time_iso_8601": "2025-04-16T18:28:50.203475Z",
      "url": "https://files.pythonhosted.org/packages/84/30/5d010d1f3d7ff8e3c273041b0e0e65acb54275d5df6b990367fca4db7a2b/antsibull_build-0.72.3.tar.gz",
      "yanked": false,
      "yanked_reason": null
    }
  ],
  "vulnerabilities": []
}
```


Related:

- https://github.com/pypi/warehouse/issues/347
- https://github.com/pypi/warehouse/issues/8802
- https://github.com/pypa/pip/issues/13264#issuecomment-2703756496

**Comment by dalf** [comment]
Follow up of https://github.com/searxng/searxng/issues/4093#issuecomment-2543900440

See https://github.com/dalf/pypisearch :

* Stored package list using [rust-fst](https://pypi.org/project/rust-fst/) (old but works on Python 3.13). Note: there is not support for the arm architecture.
* The package details are fetched in real time using the JSON API, so new version appear instantly

==>

* Response time: bellow 200ms
* In memory usage: 800Ko per worker. Load is super fast, so there is no need to keep the dataset is memory all the time.
* Disk usage: 5MB 

In SearXNG, the package list can be updated every week.

----

[EDIT] There is [tantivy branch](https://github.com/dalf/pypisearch/tree/tantivy) more as a try than anything else:
* Disk usage: 19MB (35MB for [fully offline](https://github.com/dalf/pypisearch/tree/tantivy-offline) without external requests)
* It uses more memory but some is MMAP
* Searching for `A B` give results for `B A` too (it is not the case for the rust-fst version (at least in the current version, it is possible to improve that). 
* [Tantity](https://github.com/quickwit-oss/tantivy) and fst are written in Rust, which bother me because it adds one more tool when people don't have/use wheels. However more and more tools are written in Rust, I'm not sure we can avoid Rust on the long run.

There is also a [marisa-trie branch](https://github.com/dalf/pypisearch/tree/marisa-trie)
* Disk usage: 2.6MB
* Two ways to load the trie: either full load or MMAP which uses less memory but might be really slow on HDD
* Less search features (no regex, no fuzzy search, no tokenization).
* [marisa-trie](https://github.com/pytries/marisa-trie) is written in C++

In all versions, the initial load is fast compare to the Python world --> it can be done on each query. This has to be confirm on different hardware setup.

And a [Whoosh branch](https://github.com/dalf/pypisearch/tree/whoosh):
* Disk usage: 114MB
* [whoosh](https://pypi.org/project/Whoosh/) is python only

And there are also [milli-py](https://github.com/AlexAltea/milli-py) and [pysqlite3](https://github.com/coleifer/pysqlite3) and xapian (not tested)

```
Load = load the data
Query = query the loaded data
Search = query + send the multiple HTTP queries = good estimation of the engine time

FST:

Load   (<TimeMeasure runtime=0.0003 cputime=0.0003 count=   1>, <MemoryMeasure USS=   784 KB, heap=  5064 KB, anonymous_mmaps=     0 KB, total_mapped=  5064 KB, count=  1>)
Query  (<TimeMeasure runtime=0.0009 cputime=0.0009 count=   1>, <MemoryMeasure USS=  2112 KB, heap=     0 KB, anonymous_mmaps=     0 KB, total_mapped=     0 KB, count=  1>)
Search (<TimeMeasure runtime=0.1397 cputime=0.0238 count=   1>, <MemoryMeasure USS=  3960 KB, heap=230044 KB, anonymous_mmaps=   332 KB, total_mapped=230044 KB, count=  1>)

Tantivy:

Load   (<TimeMeasure runtime=0.0013 cputime=0.0013 count=   1>, <MemoryMeasure USS=  3644 KB, heap=107744 KB, anonymous_mmaps=    72 KB, total_mapped=107744 KB, count=  1>)
Query  (<TimeMeasure runtime=0.0008 cputime=0.0008 count=   1>, <MemoryMeasure USS=  4352 KB, heap=   140 KB, anonymous_mmaps=   116 KB, total_mapped=   140 KB, count=  1>)
Search (<TimeMeasure runtime=0.1513 cputime=0.0532 count=   1>, <MemoryMeasure USS= 10664 KB, heap=238476 KB, anonymous_mmaps=  5152 KB, total_mapped=238476 KB, count=  1>)

marisa-trie / load:

Load   (<TimeMeasure runtime=0.0020 cputime=0.0020 count=   1>, <MemoryMeasure USS=  2736 KB, heap=  2620 KB, anonymous_mmaps=  2596 KB, total_mapped=  2620 KB, count=  1>)
Query  (<TimeMeasure runtime=0.0001 cputime=0.0000 count=   1>, <MemoryMeasure USS=    64 KB, heap=     0 KB, anonymous_mmaps=     0 KB, total_mapped=     0 KB, count=  1>)
Search (<TimeMeasure runtime=0.2250 cputime=0.0729 count=   1>, <MemoryMeasure USS=  8400 KB, heap=308192 KB, anonymous_mmaps=  6892 KB, total_mapped=308192 KB, count=  1>)

marisa-trie / mmap:

Load   (<TimeMeasure runtime=0.0001 cputime=0.0001 count=   1>, <MemoryMeasure USS=   976 KB, heap=  2652 KB, anonymous_mmaps=     0 KB, total_mapped=  2652 KB, count=  1>)
Query  (<TimeMeasure runtime=0.0001 cputime=0.0001 count=   1>, <MemoryMeasure USS=  1152 KB, heap=     0 KB, anonymous_mmaps=     0 KB, total_mapped=     0 KB, count=  1>)
Search (<TimeMeasure runtime=0.2206 cputime=0.0664 count=   1>, <MemoryMeasure USS=  8292 KB, heap=307240 KB, anonymous_mmaps=  5696 KB, total_mapped=307240 KB, count=  1>

whoosh

Load   (<TimeMeasure runtime=0.0034 cputime=0.0034 count=   1>, <MemoryMeasure USS=   512 KB, heap=     0 KB, anonymous_mmaps=   516 KB, total_mapped=     0 KB, count=  1>)
Query  (<TimeMeasure runtime=0.1088 cputime=0.1088 count=   1>, <MemoryMeasure USS=  2112 KB, heap=  2644 KB, anonymous_mmaps=  2048 KB, total_mapped=  2644 KB, count=  1>)
Search (<TimeMeasure runtime=0.1669 cputime=0.1490 count=   1>, <MemoryMeasure USS=  7032 KB, heap=302500 KB, anonymous_mmaps=  5756 KB, total_mapped=302500 KB, count=  1>)
```
