### ISSUE TITLE
Choosing the Indonesian language for the user interface causes an internal server error

### ISSUE THREAD

**Issue by Linerly** [searxng/searxng#594]
SearXNG version: 5307fd8

**How did you install SearXNG?**

Git clone, `pip install -r requirements.txt`, `pip install -e .`, then executing the searx/webapp.py file

**What happened?**

Going into preferences causes an internal server error

**How To Reproduce**

Choose Indonesian for the user interface language, then go into preferences again

**Expected behavior**

It shouldn't cause an internal server error

**Screenshots & Logs**
```
2021-12-11 02:51:05,301 ERROR:webapp: Exception on /preferences [GET]
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "./searx/webapp.py", line 1058, in preferences
    answerers = [
  File "./searx/webapp.py", line 1059, in <listcomp>
    {'info': a.self_info(), 'keywords': a.keywords}
  File "/home/runner/searxng/searx/answerers/statistics/answerer.py", line 51, in self_info
    'description': gettext('Compute {functions} of the arguments').format(functions='/'.join(keywords)),
KeyError: 'function'
2021-12-11 02:53:58,786 ERROR:webapp: Exception on /preferences [GET]
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "./searx/webapp.py", line 1058, in preferences
    answerers = [
  File "./searx/webapp.py", line 1059, in <listcomp>
    {'info': a.self_info(), 'keywords': a.keywords}
  File "/home/runner/searxng/searx/answerers/statistics/answerer.py", line 51, in self_info
    'description': gettext('Compute {functions} of the arguments').format(functions='/'.join(keywords)),
KeyError: 'function'
```
I have edited that string in Weblate with the correct variable name, so it should fix the problem

**Comment by dalf** [comment]
The master branch contains your contribution.
Thank you !

Feel free to reopen if you still have the issue.

**Comment by Linerly** [comment]
Thanks! It works fine now
