### ISSUE TITLE
simple theme: /preferences is broken when the checker is enabled

### ISSUE THREAD

**Issue by dalf** [searxng/searxng#819]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

1.0.0-1572-576eab04

**How did you install SearXNG?**
searxng-docker

**What happened?**
Internal Server Error when I try to go the preferences

**How To Reproduce**
go to /preferences

**Expected behavior**
I expect to see the preferences

**Screenshots & Logs**

**Additional context**
```
2022-01-25 06:14:30,598 ERROR:searx.webapp: Exception on /preferences [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/searxng/searx/webapp.py", line 1047, in preferences
    return render(
  File "/usr/local/searxng/searx/webapp.py", line 510, in render
    result = render_template('{}/{}'.format(kwargs['theme'], template_name), **kwargs)
  File "/usr/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/searxng/searx/templates/simple/preferences.html", line 92, in top-level template code
    <td class="{{ label }}"><span>{{ r }}</span></td>
  File "/usr/local/searxng/searx/templates/simple/base.html", line 50, in top-level template code
    {% block content %}
  File "/usr/local/searxng/searx/templates/simple/preferences.html", line 312, in block 'content'
    <td>{{ checkbox(engine_id + '_supported_languages', supports[search_engine.name]['supports_selected_language'], true, true) }}</td>
  File "/usr/lib/python3.9/site-packages/jinja2/runtime.py", line 828, in _invoke
    rv = self._func(*arguments)
  File "/usr/local/searxng/searx/templates/simple/macros.html", line 82, in template
    {{ icon_small('warning') }}
  File "/usr/lib/python3.9/site-packages/jinja2/utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'icon_small' is undefined
```

**Comment by return42** [comment]
I can't reproduce this issue.

**Comment by tiekoetter** [comment]
I also can't reproduce this.

**Comment by dalf** [comment]
a `docker pull`, and it's gone... I don't know what happened

**Comment by dalf** [comment]
The macro to display a checkbox in the preferences:
https://github.com/searxng/searxng/blob/81453a0ebab2b4b041828efc3653576f909d2768/searx/templates/simple/macros.html#L79-L88

If the checker is enabled, and the test failed, then a warning sign is displayed using `{{ icon_small('warning') }}`

The macro `icon_small` is not defined in `macros.html` and not in `preferences.html`. That's explain the stack trace above.
